ServerEvents.tags("item", event => {
    for(let i = 1; i < 3; i++){
        event.add('kubejs:inventory_simulators', 'kubejs:inventory_simulator_tier_' + i)
    }

    for(let i = 1; i < 4; i++){
        event.add('kubejs:inventory_pullers', 'kubejs:inventory_puller_tier_' + i)
        event.add('kubejs:inventory_pushers', 'kubejs:inventory_pusher_tier_' + i)

        event.add("kubejs:inventory_hoppers", "kubejs:inventory_hopper_down_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers", "kubejs:inventory_hopper_left_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers", "kubejs:inventory_hopper_up_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers", "kubejs:inventory_hopper_right_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers_tier_" + i, "kubejs:inventory_hopper_down_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers_tier_" + i, "kubejs:inventory_hopper_left_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers_tier_" + i, "kubejs:inventory_hopper_up_facing_tier_" + i)
        event.add("kubejs:inventory_hoppers_tier_" + i, "kubejs:inventory_hopper_right_facing_tier_" + i)

        event.add("kubejs:inventory_sorters", "kubejs:inventory_sorter_down_facing_tier_" + i)
        event.add("kubejs:inventory_sorters", "kubejs:inventory_sorter_left_facing_tier_" + i)
        event.add("kubejs:inventory_sorters", "kubejs:inventory_sorter_up_facing_tier_" + i)
        event.add("kubejs:inventory_sorters", "kubejs:inventory_sorter_right_facing_tier_" + i)
        event.add("kubejs:inventory_sorters_tier_" + i, "kubejs:inventory_sorter_down_facing_tier_" + i)
        event.add("kubejs:inventory_sorters_tier_" + i, "kubejs:inventory_sorter_left_facing_tier_" + i)
        event.add("kubejs:inventory_sorters_tier_" + i, "kubejs:inventory_sorter_up_facing_tier_" + i)
        event.add("kubejs:inventory_sorters_tier_" + i, "kubejs:inventory_sorter_right_facing_tier_" + i)

        event.add("kubejs:inventory_pistons", "kubejs:inventory_piston_down_facing_tier_" + i)
        event.add("kubejs:inventory_pistons", "kubejs:inventory_piston_left_facing_tier_" + i)
        event.add("kubejs:inventory_pistons", "kubejs:inventory_piston_up_facing_tier_" + i)
        event.add("kubejs:inventory_pistons", "kubejs:inventory_piston_right_facing_tier_" + i)
        event.add("kubejs:inventory_pistons_tier_" + i, "kubejs:inventory_piston_down_facing_tier_" + i)
        event.add("kubejs:inventory_pistons_tier_" + i, "kubejs:inventory_piston_left_facing_tier_" + i)
        event.add("kubejs:inventory_pistons_tier_" + i, "kubejs:inventory_piston_up_facing_tier_" + i)
        event.add("kubejs:inventory_pistons_tier_" + i, "kubejs:inventory_piston_right_facing_tier_" + i)

        event.add("kubejs:inventory_sticky_pistons", "kubejs:inventory_sticky_piston_down_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons", "kubejs:inventory_sticky_piston_left_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons", "kubejs:inventory_sticky_piston_up_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons", "kubejs:inventory_sticky_piston_right_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons_tier_" + i, "kubejs:inventory_sticky_piston_down_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons_tier_" + i, "kubejs:inventory_sticky_piston_left_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons_tier_" + i, "kubejs:inventory_sticky_piston_up_facing_tier_" + i)
        event.add("kubejs:inventory_sticky_pistons_tier_" + i, "kubejs:inventory_sticky_piston_right_facing_tier_" + i)
    }

    for(let i = 1; i < 5; i++){
        event.add("kubejs:inventory_furnaces", "kubejs:inventory_furnace_tier_" + i)
        event.add("kubejs:inventory_macerators", "kubejs:inventory_macerator_tier_" + i)
        event.add("kubejs:inventory_compressors", "kubejs:inventory_compressor_tier_" + i)
        event.add("kubejs:inventory_cutting_machines", "kubejs:inventory_cutting_machine_tier_" + i)
        event.add("kubejs:inventory_packers", "kubejs:inventory_packer_tier_" + i)
        event.add("kubejs:inventory_unpackers", "kubejs:inventory_unpacker_tier_" + i)
        event.add("kubejs:inventory_coke_ovens", "kubejs:inventory_coke_oven_tier_" + i)
        event.add("kubejs:inventory_blast_furnaces", "kubejs:inventory_blast_furnace_tier_" + i)
        if(i != 1){
            event.add("kubejs:inventory_wiremills", "kubejs:inventory_wiremill_tier_" + i)
            event.add("kubejs:inventory_mixers", "kubejs:inventory_mixer_tier_" + i)
            event.add("kubejs:inventory_quarrys", "kubejs:inventory_quarry_tier_" + i)
            event.add("kubejs:inventory_assemblers", "kubejs:inventory_assembler_tier_" + i)
        }
    }

    event.add("forge:ores", "kubejs:antimony_ore")
    event.add("forge:ores/antimony", "kubejs:antimony_ore")
    event.add("forge:ores", "kubejs:antimony_ore_deepslate")
    event.add("forge:ores/antimony", "kubejs:antimony_ore_deepslate")
    event.add("forge:ores_in_ground/stone", "kubejs:antimony_ore")
    event.add("forge:ores_in_ground/deepslate", "kubejs:antimony_ore_deepslate")
    event.add("forge:dusts", "kubejs:antimony_dust")
    event.add("forge:dusts/antimony", "kubejs:antimony_dust")

    event.add("forge:curved_plates", "kubejs:battery_alloy_curved_plate")
    event.add("forge:curved_plates/battery_alloy", "kubejs:battery_alloy_curved_plate")
    event.add("forge:dusts", "kubejs:battery_alloy_dust")
    event.add("forge:dusts/battery_alloy", "kubejs:battery_alloy_dust")
    event.add("forge:ingots", "kubejs:battery_alloy_ingot")
    event.add("forge:ingots/battery_alloy", "kubejs:battery_alloy_ingot")
    event.add("forge:nuggets", "kubejs:battery_alloy_nugget")
    event.add("forge:nuggets/battery_alloy", "kubejs:battery_alloy_nugget")
    event.add("forge:plates", "kubejs:battery_alloy_plate")
    event.add("forge:plates/battery_alloy", "kubejs:battery_alloy_plate")
    event.add("forge:storage_blocks", "kubejs:battery_alloy_storage_block")
    event.add("forge:storage_blocks/battery_alloy", "kubejs:battery_alloy_storage_block")

    event.add("forge:bolts", "kubejs:brass_bolt")
    event.add("forge:bolts/brass", "kubejs:brass_bolt")
    event.add("forge:curved_plates", "kubejs:brass_curved_plate")
    event.add("forge:curved_plates/brass", "kubejs:brass_curved_plate")
    event.add("forge:dusts", "kubejs:brass_dust")
    event.add("forge:dusts/brass", "kubejs:brass_dust")
    event.add("forge:gears", "kubejs:brass_gear")
    event.add("forge:gears/brass", "kubejs:brass_gear")
    event.add("forge:ingots", "kubejs:brass_ingot")
    event.add("forge:ingots/brass", "kubejs:brass_ingot")
    event.add("forge:nuggets", "kubejs:brass_nugget")
    event.add("forge:nuggets/brass", "kubejs:brass_nugget")
    event.add("forge:plates", "kubejs:brass_plate")
    event.add("forge:plates/brass", "kubejs:brass_plate")
    event.add("forge:rings", "kubejs:brass_ring")
    event.add("forge:rings/brass", "kubejs:brass_ring")
    event.add("forge:rods", "kubejs:brass_rod")
    event.add("forge:rods/brass", "kubejs:brass_rod")
    event.add("forge:rotors", "kubejs:brass_rotor")
    event.add("forge:rotors/brass", "kubejs:brass_rotor")
    event.add("forge:storage_blocks", "kubejs:brass_storage_block")
    event.add("forge:storage_blocks/brass", "kubejs:brass_storage_block")
    event.add("forge:wires", "kubejs:brass_wire")
    event.add("forge:wires/brass", "kubejs:brass_wire")

    event.add("forge:bolts", "kubejs:bronze_bolt")
    event.add("forge:bolts/bronze", "kubejs:bronze_bolt")
    event.add("forge:chunks", "kubejs:bronze_chunk")
    event.add("forge:chunks/bronze", "kubejs:bronze_chunk")
    event.add("forge:curved_plates", "kubejs:bronze_curved_plate")
    event.add("forge:curved_plates/bronze", "kubejs:bronze_curved_plate")
    event.add("forge:dusts", "kubejs:bronze_dust")
    event.add("forge:dusts/bronze", "kubejs:bronze_dust")
    event.add("forge:gears", "kubejs:bronze_gear")
    event.add("forge:gears/bronze", "kubejs:bronze_gear")
    event.add("forge:ingots", "kubejs:bronze_ingot")
    event.add("forge:ingots/bronze", "kubejs:bronze_ingot")
    event.add("forge:nuggets", "kubejs:bronze_nugget")
    event.add("forge:nuggets/bronze", "kubejs:bronze_nugget")
    event.add("forge:plates", "kubejs:bronze_plate")
    event.add("forge:plates/bronze", "kubejs:bronze_plate")
    event.add("forge:rings", "kubejs:bronze_ring")
    event.add("forge:rings/bronze", "kubejs:bronze_ring")
    event.add("forge:rods", "kubejs:bronze_rod")
    event.add("forge:rods/bronze", "kubejs:bronze_rod")
    event.add("forge:rotors", "kubejs:bronze_rotor")
    event.add("forge:rotors/bronze", "kubejs:bronze_rotor")
    event.add("forge:storage_blocks", "kubejs:bronze_storage_block")
    event.add("forge:storage_blocks/bronze", "kubejs:bronze_storage_block")
    event.add("forge:wires", "kubejs:bronze_wire")
    event.add("forge:wires/bronze", "kubejs:bronze_wire")

    event.add("forge:dusts", "kubejs:coal_dust")
    event.add("forge:dusts/coal", "kubejs:coal_dust")

    event.add("forge:bolts", "kubejs:copper_bolt")
    event.add("forge:bolts/copper", "kubejs:copper_bolt")
    event.add("forge:chunks", "kubejs:copper_chunk")
    event.add("forge:chunks/copper", "kubejs:copper_chunk")
    event.add("forge:curved_plates", "kubejs:copper_curved_plate")
    event.add("forge:curved_plates/copper", "kubejs:copper_curved_plate")
    event.add("forge:dusts", "kubejs:copper_dust")
    event.add("forge:dusts/copper", "kubejs:copper_dust")
    event.add("forge:gears", "kubejs:copper_gear")
    event.add("forge:gears/copper", "kubejs:copper_gear")
    event.add("forge:ingots", "kubejs:copper_ingot")
    event.add("forge:ingots/copper", "kubejs:copper_ingot")
    event.add("forge:nuggets", "kubejs:copper_nugget")
    event.add("forge:nuggets/copper", "kubejs:copper_nugget")
    event.add("forge:plates", "kubejs:copper_plate")
    event.add("forge:plates/copper", "kubejs:copper_plate")
    event.add("forge:raw_blocks", "minecraft:raw_copper_block")
    event.add("forge:raw_blocks/copper", "minecraft:raw_copper_block")
    event.add("forge:rings", "kubejs:copper_ring")
    event.add("forge:rings/copper", "kubejs:copper_ring")
    event.add("forge:rods", "kubejs:copper_rod")
    event.add("forge:rods/copper", "kubejs:copper_rod")
    event.add("forge:rotors", "kubejs:copper_rotor")
    event.add("forge:rotors/copper", "kubejs:copper_rotor")
    event.add("forge:wires", "kubejs:copper_wire")
    event.add("forge:wires/copper", "kubejs:copper_wire")

    event.add("forge:bolts", "kubejs:diamond_bolt")
    event.add("forge:bolts/diamond", "kubejs:diamond_bolt")
    event.add("forge:curved_plates", "kubejs:diamond_curved_plate")
    event.add("forge:curved_plates/diamond", "kubejs:diamond_curved_plate")
    event.add("forge:dusts", "kubejs:diamond_dust")
    event.add("forge:dusts/diamond", "kubejs:diamond_dust")
    event.add("forge:gears", "kubejs:diamond_gear")
    event.add("forge:gears/diamond", "kubejs:diamond_gear")
    event.add("forge:plates", "kubejs:diamond_plate")
    event.add("forge:plates/diamond", "kubejs:diamond_plate")
    event.add("forge:rings", "kubejs:diamond_ring")
    event.add("forge:rings/diamond", "kubejs:diamond_ring")
    event.add("forge:rods", "kubejs:diamond_rod")
    event.add("forge:rods/diamond", "kubejs:diamond_rod")
    event.add("forge:rotors", "kubejs:diamond_rotor")
    event.add("forge:rotors/diamond", "kubejs:diamond_rotor")
    event.add("forge:wires", "kubejs:diamond_wire")
    event.add("forge:wires/diamond", "kubejs:diamond_wire")

    event.add("forge:bolts", "kubejs:emerald_bolt")
    event.add("forge:bolts/emerald", "kubejs:emerald_bolt")
    event.add("forge:curved_plates", "kubejs:emerald_curved_plate")
    event.add("forge:curved_plates/emerald", "kubejs:emerald_curved_plate")
    event.add("forge:dusts", "kubejs:emerald_dust")
    event.add("forge:dusts/emerald", "kubejs:emerald_dust")
    event.add("forge:gears", "kubejs:emerald_gear")
    event.add("forge:gears/emerald", "kubejs:emerald_gear")
    event.add("forge:plates", "kubejs:emerald_plate")
    event.add("forge:plates/emerald", "kubejs:emerald_plate")
    event.add("forge:rings", "kubejs:emerald_ring")
    event.add("forge:rings/emerald", "kubejs:emerald_ring")
    event.add("forge:rods", "kubejs:emerald_rod")
    event.add("forge:rods/emerald", "kubejs:emerald_rod")
    event.add("forge:rotors", "kubejs:emerald_rotor")
    event.add("forge:rotors/emerald", "kubejs:emerald_rotor")
    event.add("forge:wires", "kubejs:emerald_wire")
    event.add("forge:wires/emerald", "kubejs:emerald_wire")

    event.add("forge:bolts", "kubejs:gold_bolt")
    event.add("forge:bolts/gold", "kubejs:gold_bolt")
    event.add("forge:curved_plates", "kubejs:gold_curved_plate")
    event.add("forge:curved_plates/gold", "kubejs:gold_curved_plate")
    event.add("forge:dusts", "kubejs:gold_dust")
    event.add("forge:dusts/gold", "kubejs:gold_dust")
    event.add("forge:gears", "kubejs:gold_gear")
    event.add("forge:gears/gold", "kubejs:gold_gear")
    event.add("forge:plates", "kubejs:gold_plate")
    event.add("forge:plates/gold", "kubejs:gold_plate")
    event.add("forge:raw_blocks", "minecraft:raw_gold_block")
    event.add("forge:raw_blocks/gold", "minecraft:raw_gold_block")
    event.add("forge:rings", "kubejs:gold_ring")
    event.add("forge:rings/gold", "kubejs:gold_ring")
    event.add("forge:rods", "kubejs:gold_rod")
    event.add("forge:rods/gold", "kubejs:gold_rod")
    event.add("forge:rotors", "kubejs:gold_rotor")
    event.add("forge:rotors/gold", "kubejs:gold_rotor")
    event.add("forge:wires", "kubejs:gold_wire")
    event.add("forge:wires/gold", "kubejs:gold_wire")

    event.add("forge:bolts", "kubejs:invar_bolt")
    event.add("forge:bolts/invar", "kubejs:invar_bolt")
    event.add("forge:curved_plates", "kubejs:invar_curved_plate")
    event.add("forge:curved_plates/invar", "kubejs:invar_curved_plate")
    event.add("forge:dusts", "kubejs:invar_dust")
    event.add("forge:dusts/invar", "kubejs:invar_dust")
    event.add("forge:gears", "kubejs:invar_gear")
    event.add("forge:gears/invar", "kubejs:invar_gear")
    event.add("forge:ingots", "kubejs:invar_ingot")
    event.add("forge:ingots/invar", "kubejs:invar_ingot")
    event.add("forge:nuggets", "kubejs:invar_nugget")
    event.add("forge:nuggets/invar", "kubejs:invar_nugget")
    event.add("forge:plates", "kubejs:invar_plate")
    event.add("forge:plates/invar", "kubejs:invar_plate")
    event.add("forge:rings", "kubejs:invar_ring")
    event.add("forge:rings/invar", "kubejs:invar_ring")
    event.add("forge:rods", "kubejs:invar_rod")
    event.add("forge:rods/invar", "kubejs:invar_rod")
    event.add("forge:rotors", "kubejs:invar_rotor")
    event.add("forge:rotors/invar", "kubejs:invar_rotor")
    event.add("forge:storage_blocks", "kubejs:invar_storage_block")
    event.add("forge:storage_blocks/invar", "kubejs:invar_storage_block")
    event.add("forge:wires", "kubejs:invar_wire")
    event.add("forge:wires/invar", "kubejs:invar_wire")

    event.add("forge:bolts", "kubejs:iron_bolt")
    event.add("forge:bolts/iron", "kubejs:iron_bolt")
    event.add("forge:chunks", "kubejs:iron_chunk")
    event.add("forge:chunks/iron", "kubejs:iron_chunk")
    event.add("forge:curved_plates", "kubejs:iron_curved_plate")
    event.add("forge:curved_plates/iron", "kubejs:iron_curved_plate")
    event.add("forge:dusts", "kubejs:iron_dust")
    event.add("forge:dusts/iron", "kubejs:iron_dust")
    event.add("forge:gears", "kubejs:iron_gear")
    event.add("forge:gears/iron", "kubejs:iron_gear")
    event.add("forge:plates", "kubejs:iron_plate")
    event.add("forge:plates/iron", "kubejs:iron_plate")
    event.add("forge:raw_blocks", "minecraft:raw_iron_block")
    event.add("forge:raw_blocks/iron", "minecraft:raw_iron_block")
    event.add("forge:rings", "kubejs:iron_ring")
    event.add("forge:rings/iron", "kubejs:iron_ring")
    event.add("forge:rods", "kubejs:iron_rod")
    event.add("forge:rods/iron", "kubejs:iron_rod")
    event.add("forge:rotors", "kubejs:iron_rotor")
    event.add("forge:rotors/iron", "kubejs:iron_rotor")
    event.add("forge:wires", "kubejs:iron_wire")
    event.add("forge:wires/iron", "kubejs:iron_wire")

    event.add("forge:bolts", "kubejs:lapis_lazuli_bolt")
    event.add("forge:bolts/lapis_lazuli", "kubejs:lapis_lazuli_bolt")
    event.add("forge:curved_plates", "kubejs:lapis_lazuli_curved_plate")
    event.add("forge:curved_plates/lapis_lazuli", "kubejs:lapis_lazuli_curved_plate")
    event.add("forge:dusts", "kubejs:lapis_lazuli_dust")
    event.add("forge:dusts/lapis_lazuli", "kubejs:lapis_lazuli_dust")
    event.add("forge:gears", "kubejs:lapis_lazuli_gear")
    event.add("forge:gears/lapis_lazuli", "kubejs:lapis_lazuli_gear")
    event.add("forge:plates", "kubejs:lapis_lazuli_plate")
    event.add("forge:plates/lapis_lazuli", "kubejs:lapis_lazuli_plate")
    event.add("forge:rings", "kubejs:lapis_lazuli_ring")
    event.add("forge:rings/lapis_lazuli", "kubejs:lapis_lazuli_ring")
    event.add("forge:rods", "kubejs:lapis_lazuli_rod")
    event.add("forge:rods/lapis_lazuli", "kubejs:lapis_lazuli_rod")
    event.add("forge:rotors", "kubejs:lapis_lazuli_rotor")
    event.add("forge:rotors/lapis_lazuli", "kubejs:lapis_lazuli_rotor")
    event.add("forge:wires", "kubejs:lapis_lazuli_wire")
    event.add("forge:wires/lapis_lazuli", "kubejs:lapis_lazuli_wire")

    event.add("forge:bolts", "kubejs:lead_bolt")
    event.add("forge:bolts/lead", "kubejs:lead_bolt")
    event.add("forge:curved_plates", "kubejs:lead_curved_plate")
    event.add("forge:curved_plates/lead", "kubejs:lead_curved_plate")
    event.add("forge:dusts", "kubejs:lead_dust")
    event.add("forge:dusts/lead", "kubejs:lead_dust")
    event.add("forge:gears", "kubejs:lead_gear")
    event.add("forge:gears/lead", "kubejs:lead_gear")
    event.add("forge:ingots", "kubejs:lead_ingot")
    event.add("forge:ingots/lead", "kubejs:lead_ingot")
    event.add("forge:nuggets", "kubejs:lead_nugget")
    event.add("forge:nuggets/lead", "kubejs:lead_nugget")
    event.add("forge:ores", "kubejs:lead_ore")
    event.add("forge:ores/lead", "kubejs:lead_ore")
    event.add("forge:ores", "kubejs:lead_ore_deepslate")
    event.add("forge:ores/lead", "kubejs:lead_ore_deepslate")
    event.add("forge:ores_in_ground/stone", "kubejs:lead_ore")
    event.add("forge:ores_in_ground/deepslate", "kubejs:lead_ore_deepslate")
    event.add("forge:plates", "kubejs:lead_plate")
    event.add("forge:plates/lead", "kubejs:lead_plate")
    event.add("forge:raw_blocks", "kubejs:lead_raw_block")
    event.add("forge:raw_blocks/lead", "kubejs:lead_raw_block")
    event.add("forge:raw_materials", "kubejs:lead_raw_material")
    event.add("forge:raw_materials/lead", "kubejs:lead_raw_material")
    event.add("forge:rings", "kubejs:lead_ring")
    event.add("forge:rings/lead", "kubejs:lead_ring")
    event.add("forge:rods", "kubejs:lead_rod")
    event.add("forge:rods/lead", "kubejs:lead_rod")
    event.add("forge:rotors", "kubejs:lead_rotor")
    event.add("forge:rotors/lead", "kubejs:lead_rotor")
    event.add("forge:storage_blocks", "kubejs:lead_storage_block")
    event.add("forge:storage_blocks/lead", "kubejs:lead_storage_block")
    event.add("forge:wires", "kubejs:lead_wire")
    event.add("forge:wires/lead", "kubejs:lead_wire")

    event.add("forge:bolts", "kubejs:nickel_bolt")
    event.add("forge:bolts/nickel", "kubejs:nickel_bolt")
    event.add("forge:curved_plates", "kubejs:nickel_curved_plate")
    event.add("forge:curved_plates/nickel", "kubejs:nickel_curved_plate")
    event.add("forge:dusts", "kubejs:nickel_dust")
    event.add("forge:dusts/nickel", "kubejs:nickel_dust")
    event.add("forge:gears", "kubejs:nickel_gear")
    event.add("forge:gears/nickel", "kubejs:nickel_gear")
    event.add("forge:ingots", "kubejs:nickel_ingot")
    event.add("forge:ingots/nickel", "kubejs:nickel_ingot")
    event.add("forge:nuggets", "kubejs:nickel_nugget")
    event.add("forge:nuggets/nickel", "kubejs:nickel_nugget")
    event.add("forge:ores", "kubejs:nickel_ore")
    event.add("forge:ores/nickel", "kubejs:nickel_ore")
    event.add("forge:ores", "kubejs:nickel_ore_deepslate")
    event.add("forge:ores/nickel", "kubejs:nickel_ore_deepslate")
    event.add("forge:ores_in_ground/stone", "kubejs:nickel_ore")
    event.add("forge:ores_in_ground/deepslate", "kubejs:nickel_ore_deepslate")
    event.add("forge:plates", "kubejs:nickel_plate")
    event.add("forge:plates/nickel", "kubejs:nickel_plate")
    event.add("forge:raw_blocks", "kubejs:nickel_raw_block")
    event.add("forge:raw_blocks/nickel", "kubejs:nickel_raw_block")
    event.add("forge:raw_materials", "kubejs:nickel_raw_material")
    event.add("forge:raw_materials/nickel", "kubejs:nickel_raw_material")
    event.add("forge:rings", "kubejs:nickel_ring")
    event.add("forge:rings/nickel", "kubejs:nickel_ring")
    event.add("forge:rods", "kubejs:nickel_rod")
    event.add("forge:rods/nickel", "kubejs:nickel_rod")
    event.add("forge:rotors", "kubejs:nickel_rotor")
    event.add("forge:rotors/nickel", "kubejs:nickel_rotor")
    event.add("forge:storage_blocks", "kubejs:nickel_storage_block")
    event.add("forge:storage_blocks/nickel", "kubejs:nickel_storage_block")
    event.add("forge:wires", "kubejs:nickel_wire")
    event.add("forge:wires/nickel", "kubejs:nickel_wire")

    event.add("forge:bolts", "kubejs:steel_bolt")
    event.add("forge:bolts/steel", "kubejs:steel_bolt")
    event.add("forge:curved_plates", "kubejs:steel_curved_plate")
    event.add("forge:curved_plates/steel", "kubejs:steel_curved_plate")
    event.add("forge:dusts", "kubejs:steel_dust")
    event.add("forge:dusts/steel", "kubejs:steel_dust")
    event.add("forge:gears", "kubejs:steel_gear")
    event.add("forge:gears/steel", "kubejs:steel_gear")
    event.add("forge:ingots", "kubejs:steel_ingot")
    event.add("forge:ingots/steel", "kubejs:steel_ingot")
    event.add("forge:nuggets", "kubejs:steel_nugget")
    event.add("forge:nuggets/steel", "kubejs:steel_nugget")
    event.add("forge:plates", "kubejs:steel_plate")
    event.add("forge:plates/steel", "kubejs:steel_plate")
    event.add("forge:rings", "kubejs:steel_ring")
    event.add("forge:rings/steel", "kubejs:steel_ring")
    event.add("forge:rods", "kubejs:steel_rod")
    event.add("forge:rods/steel", "kubejs:steel_rod")
    event.add("forge:rotors", "kubejs:steel_rotor")
    event.add("forge:rotors/steel", "kubejs:steel_rotor")
    event.add("forge:storage_blocks", "kubejs:steel_storage_block")
    event.add("forge:storage_blocks/steel", "kubejs:steel_storage_block")
    event.add("forge:wires", "kubejs:steel_wire")
    event.add("forge:wires/steel", "kubejs:steel_wire")

    event.add("forge:bolts", "kubejs:tin_bolt")
    event.add("forge:bolts/tin", "kubejs:tin_bolt")
    event.add("forge:chunks", "kubejs:tin_chunk")
    event.add("forge:chunks/tin", "kubejs:tin_chunk")
    event.add("forge:curved_plates", "kubejs:tin_curved_plate")
    event.add("forge:curved_plates/tin", "kubejs:tin_curved_plate")
    event.add("forge:dusts", "kubejs:tin_dust")
    event.add("forge:dusts/tin", "kubejs:tin_dust")
    event.add("forge:gears", "kubejs:tin_gear")
    event.add("forge:gears/tin", "kubejs:tin_gear")
    event.add("forge:ingots", "kubejs:tin_ingot")
    event.add("forge:ingots/tin", "kubejs:tin_ingot")
    event.add("forge:nuggets", "kubejs:tin_nugget")
    event.add("forge:nuggets/tin", "kubejs:tin_nugget")
    event.add("forge:ores", "kubejs:tin_ore")
    event.add("forge:ores/tin", "kubejs:tin_ore")
    event.add("forge:ores", "kubejs:tin_ore_deepslate")
    event.add("forge:ores/tin", "kubejs:tin_ore_deepslate")
    event.add("forge:ores_in_ground/stone", "kubejs:tin_ore")
    event.add("forge:ores_in_ground/deepslate", "kubejs:tin_ore_deepslate")
    event.add("forge:plates", "kubejs:tin_plate")
    event.add("forge:plates/tin", "kubejs:tin_plate")
    event.add("forge:raw_blocks", "kubejs:tin_raw_block")
    event.add("forge:raw_blocks/tin", "kubejs:tin_raw_block")
    event.add("forge:raw_materials", "kubejs:tin_raw_material")
    event.add("forge:raw_materials/tin", "kubejs:tin_raw_material")
    event.add("forge:rings", "kubejs:tin_ring")
    event.add("forge:rings/tin", "kubejs:tin_ring")
    event.add("forge:rods", "kubejs:tin_rod")
    event.add("forge:rods/tin", "kubejs:tin_rod")
    event.add("forge:rotors", "kubejs:tin_rotor")
    event.add("forge:rotors/tin", "kubejs:tin_rotor")
    event.add("forge:storage_blocks", "kubejs:tin_storage_block")
    event.add("forge:storage_blocks/tin", "kubejs:tin_storage_block")
    event.add("forge:wires", "kubejs:tin_wire")
    event.add("forge:wires/tin", "kubejs:tin_wire")

    event.add("forge:bolts", "kubejs:zinc_bolt")
    event.add("forge:bolts/zinc", "kubejs:zinc_bolt")
    event.add("forge:curved_plates", "kubejs:zinc_curved_plate")
    event.add("forge:curved_plates/zinc", "kubejs:zinc_curved_plate")
    event.add("forge:dusts", "kubejs:zinc_dust")
    event.add("forge:dusts/zinc", "kubejs:zinc_dust")
    event.add("forge:gears", "kubejs:zinc_gear")
    event.add("forge:gears/zinc", "kubejs:zinc_gear")
    event.add("forge:ingots", "kubejs:zinc_ingot")
    event.add("forge:ingots/zinc", "kubejs:zinc_ingot")
    event.add("forge:nuggets", "kubejs:zinc_nugget")
    event.add("forge:nuggets/zinc", "kubejs:zinc_nugget")
    event.add("forge:ores", "kubejs:zinc_ore")
    event.add("forge:ores/zinc", "kubejs:zinc_ore")
    event.add("forge:ores", "kubejs:zinc_ore_deepslate")
    event.add("forge:ores/zinc", "kubejs:zinc_ore_deepslate")
    event.add("forge:ores_in_ground/stone", "kubejs:zinc_ore")
    event.add("forge:ores_in_ground/deepslate", "kubejs:zinc_ore_deepslate")
    event.add("forge:plates", "kubejs:zinc_plate")
    event.add("forge:plates/zinc", "kubejs:zinc_plate")
    event.add("forge:raw_blocks", "kubejs:zinc_raw_block")
    event.add("forge:raw_blocks/zinc", "kubejs:zinc_raw_block")
    event.add("forge:raw_materials", "kubejs:zinc_raw_material")
    event.add("forge:raw_materials/zinc", "kubejs:zinc_raw_material")
    event.add("forge:rings", "kubejs:zinc_ring")
    event.add("forge:rings/zinc", "kubejs:zinc_ring")
    event.add("forge:rods", "kubejs:zinc_rod")
    event.add("forge:rods/zinc", "kubejs:zinc_rod")
    event.add("forge:rotors", "kubejs:zinc_rotor")
    event.add("forge:rotors/zinc", "kubejs:zinc_rotor")
    event.add("forge:storage_blocks", "kubejs:zinc_storage_block")
    event.add("forge:storage_blocks/zinc", "kubejs:zinc_storage_block")
    event.add("forge:wires", "kubejs:zinc_wire")
    event.add("forge:wires/zinc", "kubejs:zinc_wire")

    event.add("kubejs:templates", "kubejs:drawer_template_1x1")
    event.add("kubejs:templates", "kubejs:drawer_template_1x2")
    event.add("kubejs:templates", "kubejs:drawer_template_2x2")
    event.add("kubejs:templates", "kubejs:block_template")
    event.add("kubejs:templates", "kubejs:boat_template")
    event.add("kubejs:templates", "kubejs:button_template")
    event.add("kubejs:templates", "kubejs:carpet_template")
    event.add("kubejs:templates", "kubejs:color_template")
    event.add("kubejs:templates", "kubejs:door_template")
    event.add("kubejs:templates", "kubejs:fence_gate_template")
    event.add("kubejs:templates", "kubejs:fence_template")
    event.add("kubejs:templates", "kubejs:glass_pane_template")
    event.add("kubejs:templates", "kubejs:log_template")
    event.add("kubejs:templates", "kubejs:pressure_plate_template")
    event.add("kubejs:templates", "kubejs:sign_template")
    event.add("kubejs:templates", "kubejs:slab_template")
    event.add("kubejs:templates", "kubejs:stairs_template")
    event.add("kubejs:templates", "kubejs:trapdoor_template")
    event.add("kubejs:templates", "kubejs:wall_template")
    event.add("kubejs:templates", "kubejs:waxing_template")

    event.add("kubejs:hammers", "kubejs:iron_hammer")
    event.add("kubejs:hammers", "kubejs:steel_hammer")

    event.add("forge:gems", "kubejs:coal_coke")
    event.add("forge:gems/coal_coke", "kubejs:coal_coke")
    event.add("forge:dusts", "kubejs:coal_coke_dust")
    event.add("forge:dusts/coal_coke", "kubejs:coal_coke_dust")

    event.add("kubejs:drill_heads", "kubejs:bronze_drill_head")
    event.add("kubejs:drills", "kubejs:bronze_drill")
    event.add("kubejs:drill_heads", "kubejs:copper_drill_head")
    event.add("kubejs:drills", "kubejs:copper_drill")
    event.add("kubejs:drill_heads", "kubejs:steel_drill_head")
    event.add("kubejs:drills", "kubejs:steel_drill")
    event.add("kubejs:drill_heads", "kubejs:gold_drill_head")
    event.add("kubejs:drills", "kubejs:gold_drill")

    event.add("kubejs:machine_casings", "kubejs:bronze_machine_casing")
    event.add("kubejs:machine_casings", "kubejs:steel_machine_casing")
})