StartupEvents.modifyCreativeTab('kubejs:tab', event => {
    Ingredient.of(/.*inventory.*/).itemIds.forEach((item) => {
        event.remove(Item.of(item))
    })

    event.addAfter("kubejs:steel_machine_casing", Item.of("kubejs:inventory_simulator_tier_1"))
    event.addAfter("kubejs:inventory_simulator_tier_1", Item.of("kubejs:inventory_simulator_tier_2"))

    event.addAfter("kubejs:inventory_simulator_tier_2", Item.of("kubejs:inventory_hopper_down_facing_tier_1"))
    event.addAfter("kubejs:inventory_hopper_down_facing_tier_1", Item.of("kubejs:inventory_hopper_left_facing_tier_1"))
    event.addAfter("kubejs:inventory_hopper_left_facing_tier_1", Item.of("kubejs:inventory_hopper_up_facing_tier_1"))
    event.addAfter("kubejs:inventory_hopper_up_facing_tier_1", Item.of("kubejs:inventory_hopper_right_facing_tier_1"))
    event.addAfter("kubejs:inventory_hopper_right_facing_tier_1", Item.of("kubejs:inventory_hopper_down_facing_tier_2"))
    event.addAfter("kubejs:inventory_hopper_down_facing_tier_2", Item.of("kubejs:inventory_hopper_left_facing_tier_2"))
    event.addAfter("kubejs:inventory_hopper_left_facing_tier_2", Item.of("kubejs:inventory_hopper_up_facing_tier_2"))
    event.addAfter("kubejs:inventory_hopper_up_facing_tier_2", Item.of("kubejs:inventory_hopper_right_facing_tier_2"))
    event.addAfter("kubejs:inventory_hopper_right_facing_tier_2", Item.of("kubejs:inventory_hopper_down_facing_tier_3"))
    event.addAfter("kubejs:inventory_hopper_down_facing_tier_3", Item.of("kubejs:inventory_hopper_left_facing_tier_3"))
    event.addAfter("kubejs:inventory_hopper_left_facing_tier_3", Item.of("kubejs:inventory_hopper_up_facing_tier_3"))
    event.addAfter("kubejs:inventory_hopper_up_facing_tier_3", Item.of("kubejs:inventory_hopper_right_facing_tier_3"))

    event.addAfter("kubejs:inventory_hopper_right_facing_tier_3", Item.of("kubejs:inventory_sorter_down_facing_tier_1", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_down_facing_tier_1", Item.of("kubejs:inventory_sorter_left_facing_tier_1", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_left_facing_tier_1", Item.of("kubejs:inventory_sorter_up_facing_tier_1", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_up_facing_tier_1", Item.of("kubejs:inventory_sorter_right_facing_tier_1", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_right_facing_tier_1", Item.of("kubejs:inventory_sorter_down_facing_tier_2", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_down_facing_tier_2", Item.of("kubejs:inventory_sorter_left_facing_tier_2", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_left_facing_tier_2", Item.of("kubejs:inventory_sorter_up_facing_tier_2", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_up_facing_tier_2", Item.of("kubejs:inventory_sorter_right_facing_tier_2", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_right_facing_tier_2", Item.of("kubejs:inventory_sorter_down_facing_tier_3", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_down_facing_tier_3", Item.of("kubejs:inventory_sorter_left_facing_tier_3", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_left_facing_tier_3", Item.of("kubejs:inventory_sorter_up_facing_tier_3", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))
    event.addAfter("kubejs:inventory_sorter_up_facing_tier_3", Item.of("kubejs:inventory_sorter_right_facing_tier_3", '{"filter": {"type": "item", "item": "minecraft:air"}, "side": "left"}'))

    event.addAfter("kubejs:inventory_sorter_right_facing_tier_3", Item.of("kubejs:inventory_piston_up_facing_tier_1"))
    event.addAfter("kubejs:inventory_piston_up_facing_tier_1", Item.of("kubejs:inventory_sticky_piston_up_facing_tier_1"))
    event.addAfter("kubejs:inventory_sticky_piston_up_facing_tier_1", Item.of("kubejs:inventory_piston_right_facing_tier_1"))
    event.addAfter("kubejs:inventory_piston_right_facing_tier_1", Item.of("kubejs:inventory_sticky_piston_right_facing_tier_1"))
    event.addAfter("kubejs:inventory_sticky_piston_right_facing_tier_1", Item.of("kubejs:inventory_piston_down_facing_tier_1"))
    event.addAfter("kubejs:inventory_piston_down_facing_tier_1", Item.of("kubejs:inventory_sticky_piston_down_facing_tier_1"))
    event.addAfter("kubejs:inventory_sticky_piston_down_facing_tier_1", Item.of("kubejs:inventory_piston_left_facing_tier_1"))
    event.addAfter("kubejs:inventory_piston_left_facing_tier_1", Item.of("kubejs:inventory_sticky_piston_left_facing_tier_1"))
    event.addAfter("kubejs:inventory_sticky_piston_left_facing_tier_1", Item.of("kubejs:inventory_piston_up_facing_tier_2"))
    event.addAfter("kubejs:inventory_piston_up_facing_tier_2", Item.of("kubejs:inventory_sticky_piston_up_facing_tier_2"))
    event.addAfter("kubejs:inventory_sticky_piston_up_facing_tier_2", Item.of("kubejs:inventory_piston_right_facing_tier_2"))
    event.addAfter("kubejs:inventory_piston_right_facing_tier_2", Item.of("kubejs:inventory_sticky_piston_right_facing_tier_2"))
    event.addAfter("kubejs:inventory_sticky_piston_right_facing_tier_2", Item.of("kubejs:inventory_piston_down_facing_tier_2"))
    event.addAfter("kubejs:inventory_piston_down_facing_tier_2", Item.of("kubejs:inventory_sticky_piston_down_facing_tier_2"))
    event.addAfter("kubejs:inventory_sticky_piston_down_facing_tier_2", Item.of("kubejs:inventory_piston_left_facing_tier_2"))
    event.addAfter("kubejs:inventory_piston_left_facing_tier_2", Item.of("kubejs:inventory_sticky_piston_left_facing_tier_2"))
    event.addAfter("kubejs:inventory_sticky_piston_left_facing_tier_2", Item.of("kubejs:inventory_piston_up_facing_tier_3"))
    event.addAfter("kubejs:inventory_piston_up_facing_tier_3", Item.of("kubejs:inventory_sticky_piston_up_facing_tier_3"))
    event.addAfter("kubejs:inventory_sticky_piston_up_facing_tier_3", Item.of("kubejs:inventory_piston_right_facing_tier_3"))
    event.addAfter("kubejs:inventory_piston_right_facing_tier_3", Item.of("kubejs:inventory_sticky_piston_right_facing_tier_3"))
    event.addAfter("kubejs:inventory_sticky_piston_right_facing_tier_3", Item.of("kubejs:inventory_piston_down_facing_tier_3"))
    event.addAfter("kubejs:inventory_piston_down_facing_tier_3", Item.of("kubejs:inventory_sticky_piston_down_facing_tier_3"))
    event.addAfter("kubejs:inventory_sticky_piston_down_facing_tier_3", Item.of("kubejs:inventory_piston_left_facing_tier_3"))
    event.addAfter("kubejs:inventory_piston_left_facing_tier_3", Item.of("kubejs:inventory_sticky_piston_left_facing_tier_3"))

    event.addAfter("kubejs:inventory_sticky_piston_left_facing_tier_3", Item.of("kubejs:inventory_puller_tier_1", '{"filter": {"type": "item", "item": "minecraft:air"}}'))
    event.addAfter("kubejs:inventory_puller_tier_1", Item.of("kubejs:inventory_puller_tier_2", '{"filter": {"type": "item", "item": "minecraft:air"}}'))
    event.addAfter("kubejs:inventory_puller_tier_2", Item.of("kubejs:inventory_puller_tier_3", '{"filter": {"type": "item", "item": "minecraft:air"}}'))

    event.addAfter("kubejs:inventory_puller_tier_3", Item.of("kubejs:inventory_pusher_tier_1"))
    event.addAfter("kubejs:inventory_pusher_tier_1", Item.of("kubejs:inventory_pusher_tier_2"))
    event.addAfter("kubejs:inventory_pusher_tier_2", Item.of("kubejs:inventory_pusher_tier_3"))

    event.addAfter("kubejs:inventory_pusher_tier_3", Item.of("kubejs:inventory_furnace_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_furnace_tier_1", Item.of("kubejs:inventory_furnace_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_furnace_tier_2", Item.of("kubejs:inventory_furnace_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_furnace_tier_3", Item.of("kubejs:inventory_furnace_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_furnace_tier_4", Item.of("kubejs:inventory_macerator_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_macerator_tier_1", Item.of("kubejs:inventory_macerator_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_macerator_tier_2", Item.of("kubejs:inventory_macerator_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_macerator_tier_3", Item.of("kubejs:inventory_macerator_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_macerator_tier_4", Item.of("kubejs:inventory_compressor_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_compressor_tier_1", Item.of("kubejs:inventory_compressor_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_compressor_tier_2", Item.of("kubejs:inventory_compressor_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_compressor_tier_3", Item.of("kubejs:inventory_compressor_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    
    event.addAfter("kubejs:inventory_compressor_tier_4", Item.of("kubejs:inventory_cutting_machine_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_cutting_machine_tier_1", Item.of("kubejs:inventory_cutting_machine_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_cutting_machine_tier_2", Item.of("kubejs:inventory_cutting_machine_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_cutting_machine_tier_3", Item.of("kubejs:inventory_cutting_machine_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_cutting_machine_tier_4", Item.of("kubejs:inventory_packer_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_packer_tier_1", Item.of("kubejs:inventory_packer_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_packer_tier_2", Item.of("kubejs:inventory_packer_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_packer_tier_3", Item.of("kubejs:inventory_packer_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_packer_tier_4", Item.of("kubejs:inventory_unpacker_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_unpacker_tier_1", Item.of("kubejs:inventory_unpacker_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_unpacker_tier_2", Item.of("kubejs:inventory_unpacker_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_unpacker_tier_3", Item.of("kubejs:inventory_unpacker_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_unpacker_tier_4", Item.of("kubejs:inventory_coke_oven_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_coke_oven_tier_1", Item.of("kubejs:inventory_coke_oven_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_coke_oven_tier_2", Item.of("kubejs:inventory_coke_oven_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_coke_oven_tier_3", Item.of("kubejs:inventory_coke_oven_tier_4", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_coke_oven_tier_4", Item.of("kubejs:inventory_blast_furnace_tier_1", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_blast_furnace_tier_1", Item.of("kubejs:inventory_blast_furnace_tier_2", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_blast_furnace_tier_2", Item.of("kubejs:inventory_blast_furnace_tier_3", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_blast_furnace_tier_3", Item.of("kubejs:inventory_blast_furnace_tier_4", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_blast_furnace_tier_4", Item.of("kubejs:inventory_wiremill_tier_1", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_wiremill_tier_1", Item.of("kubejs:inventory_wiremill_tier_2", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_wiremill_tier_2", Item.of("kubejs:inventory_wiremill_tier_3", '{"currentInputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_wiremill_tier_3", Item.of("kubejs:inventory_mixer_tier_1", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_mixer_tier_1", Item.of("kubejs:inventory_mixer_tier_2", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_mixer_tier_2", Item.of("kubejs:inventory_mixer_tier_3", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_mixer_tier_3", Item.of("kubejs:inventory_assembler_tier_1", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_assembler_tier_1", Item.of("kubejs:inventory_assembler_tier_2", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_assembler_tier_2", Item.of("kubejs:inventory_assembler_tier_3", '{"currentRecipe": -1, "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))

    event.addAfter("kubejs:inventory_assembler_tier_3", Item.of("kubejs:inventory_quarry_tier_1", '{"currentInputItem": "minecraft:air", "currentOutputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_quarry_tier_1", Item.of("kubejs:inventory_quarry_tier_2", '{"currentInputItem": "minecraft:air", "currentOutputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
    event.addAfter("kubejs:inventory_quarry_tier_2", Item.of("kubejs:inventory_quarry_tier_3", '{"currentInputItem": "minecraft:air", "currentOutputItem": "minecraft:air", "fuel": 0, "recipeProgress": 0, "currentTime": 0}'))
})