StartupEvents.registry("item", event => {
    //materials
    /*
    event.create("aluminum_bolt").texture("kubejs:item/materials/aluminum/aluminum_bolt")
    event.create("aluminum_crushed_ore").displayName("Crushed Aluminum Ore").texture("kubejs:item/materials/aluminum/aluminum_crushed_ore")
    event.create("aluminum_curved_plate").texture("kubejs:item/materials/aluminum/aluminum_curved_plate")
    event.create("aluminum_dust").texture("kubejs:item/materials/aluminum/aluminum_dust")
    event.create("aluminum_gear").texture("kubejs:item/materials/aluminum/aluminum_gear")
    event.create("aluminum_ingot").texture("kubejs:item/materials/aluminum/aluminum_ingot")
    event.create("aluminum_nugget").texture("kubejs:item/materials/aluminum/aluminum_nugget")
    event.create("aluminum_plate").texture("kubejs:item/materials/aluminum/aluminum_plate")
    event.create("aluminum_raw_material").displayName("Raw Aluminum").texture("kubejs:item/materials/aluminum/aluminum_raw_material")
    event.create("aluminum_ring").displayName("Raw Aluminum").texture("kubejs:item/materials/aluminum/aluminum_ring")
    event.create("aluminum_rod").texture("kubejs:item/materials/aluminum/aluminum_rod")
    event.create("aluminum_rotor").texture("kubejs:item/materials/aluminum/aluminum_rotor")
    event.create("aluminum_wire").texture("kubejs:item/materials/aluminum/aluminum_wire")
    */

    event.create("antimony_dust").texture("kubejs:item/materials/antimony/antimony_dust")

    event.create("battery_alloy_curved_plate").texture("kubejs:item/materials/battery_alloy/battery_alloy_curved_plate")
    event.create("battery_alloy_dust").texture("kubejs:item/materials/battery_alloy/battery_alloy_dust")
    event.create("battery_alloy_ingot").texture("kubejs:item/materials/battery_alloy/battery_alloy_ingot")
    event.create("battery_alloy_nugget").texture("kubejs:item/materials/battery_alloy/battery_alloy_nugget")
    event.create("battery_alloy_plate").texture("kubejs:item/materials/battery_alloy/battery_alloy_plate")

    event.create("brass_bolt").texture("kubejs:item/materials/brass/brass_bolt")
    event.create("brass_curved_plate").texture("kubejs:item/materials/brass/brass_curved_plate")
    event.create("brass_dust").texture("kubejs:item/materials/brass/brass_dust")
    event.create("brass_gear").texture("kubejs:item/materials/brass/brass_gear")
    event.create("brass_ingot").texture("kubejs:item/materials/brass/brass_ingot")
    event.create("brass_nugget").texture("kubejs:item/materials/brass/brass_nugget")
    event.create("brass_plate").texture("kubejs:item/materials/brass/brass_plate")
    event.create("brass_ring").texture("kubejs:item/materials/brass/brass_ring")
    event.create("brass_rod").texture("kubejs:item/materials/brass/brass_rod")
    event.create("brass_rotor").texture("kubejs:item/materials/brass/brass_rotor")
    event.create("brass_wire").texture("kubejs:item/materials/brass/brass_wire")

    event.create("bronze_bolt").texture("kubejs:item/materials/bronze/bronze_bolt")
    event.create("bronze_chunk").texture("kubejs:item/materials/bronze/bronze_chunk")
    event.create("bronze_curved_plate").texture("kubejs:item/materials/bronze/bronze_curved_plate")
    event.create("bronze_dust").texture("kubejs:item/materials/bronze/bronze_dust")
    event.create("bronze_gear").texture("kubejs:item/materials/bronze/bronze_gear")
    event.create("bronze_ingot").texture("kubejs:item/materials/bronze/bronze_ingot")
    event.create("bronze_nugget").texture("kubejs:item/materials/bronze/bronze_nugget")
    event.create("bronze_plate").texture("kubejs:item/materials/bronze/bronze_plate")
    event.create("bronze_ring").texture("kubejs:item/materials/bronze/bronze_ring")
    event.create("bronze_rod").texture("kubejs:item/materials/bronze/bronze_rod")
    event.create("bronze_rotor").texture("kubejs:item/materials/bronze/bronze_rotor")
    event.create("bronze_wire").texture("kubejs:item/materials/bronze/bronze_wire")

    /*
    event.create("cobalt_bolt").texture("kubejs:item/materials/cobalt/cobalt_bolt")
    event.create("cobalt_crushed_ore").displayName("Crushed Cobalt Ore").texture("kubejs:item/materials/cobalt/cobalt_crushed_ore")
    event.create("cobalt_curved_plate").texture("kubejs:item/materials/cobalt/cobalt_curved_plate")
    event.create("cobalt_dust").texture("kubejs:item/materials/cobalt/cobalt_dust")
    event.create("cobalt_gear").texture("kubejs:item/materials/cobalt/cobalt_gear")
    event.create("cobalt_ingot").texture("kubejs:item/materials/cobalt/cobalt_ingot")
    event.create("cobalt_nugget").texture("kubejs:item/materials/cobalt/cobalt_nugget")
    event.create("cobalt_plate").texture("kubejs:item/materials/cobalt/cobalt_plate")
    event.create("cobalt_raw_material").displayName("Raw Cobalt").texture("kubejs:item/materials/cobalt/cobalt_raw_material")
    event.create("cobalt_ring").displayName("Raw Cobalt").texture("kubejs:item/materials/cobalt/cobalt_ring")
    event.create("cobalt_rod").texture("kubejs:item/materials/cobalt/cobalt_rod")
    event.create("cobalt_rotor").texture("kubejs:item/materials/cobalt/cobalt_rotor")
    event.create("cobalt_wire").texture("kubejs:item/materials/cobalt/cobalt_wire")
    */

    event.create("coal_dust").texture("kubejs:item/materials/coal/coal_dust")

    /*
    event.create("constantan_bolt").texture("kubejs:item/materials/constantan/constantan_bolt")
    event.create("constantan_curved_plate").texture("kubejs:item/materials/constantan/constantan_curved_plate")
    event.create("constantan_dust").texture("kubejs:item/materials/constantan/constantan_dust")
    event.create("constantan_gear").texture("kubejs:item/materials/constantan/constantan_gear")
    event.create("constantan_ingot").texture("kubejs:item/materials/constantan/constantan_ingot")
    event.create("constantan_nugget").texture("kubejs:item/materials/constantan/constantan_nugget")
    event.create("constantan_plate").texture("kubejs:item/materials/constantan/constantan_plate")
    event.create("constantan_ring").texture("kubejs:item/materials/constantan/constantan_ring")
    event.create("constantan_rod").texture("kubejs:item/materials/constantan/constantan_rod")
    event.create("constantan_rotor").texture("kubejs:item/materials/constantan/constantan_rotor")
    event.create("constantan_wire").texture("kubejs:item/materials/constantan/constantan_wire")
    */

    event.create("copper_bolt").texture("kubejs:item/materials/copper/copper_bolt")
    event.create("copper_chunk").texture("kubejs:item/materials/copper/copper_chunk")
    event.create("copper_crushed_ore").displayName("Crushed Copper Ore").texture("kubejs:item/materials/copper/copper_crushed_ore")
    event.create("copper_curved_plate").texture("kubejs:item/materials/copper/copper_curved_plate")
    event.create("copper_dust").texture("kubejs:item/materials/copper/copper_dust")
    event.create("copper_gear").texture("kubejs:item/materials/copper/copper_gear")
    event.create("copper_nugget").texture("kubejs:item/materials/copper/copper_nugget")
    event.create("copper_plate").texture("kubejs:item/materials/copper/copper_plate")
    event.create("copper_ring").texture("kubejs:item/materials/copper/copper_ring")
    event.create("copper_rod").texture("kubejs:item/materials/copper/copper_rod")
    event.create("copper_rotor").texture("kubejs:item/materials/copper/copper_rotor")
    event.create("copper_wire").texture("kubejs:item/materials/copper/copper_wire")

    event.create("diamond_bolt").texture("kubejs:item/materials/diamond/diamond_bolt")
    event.create("diamond_curved_plate").texture("kubejs:item/materials/diamond/diamond_curved_plate")
    event.create("diamond_dust").texture("kubejs:item/materials/diamond/diamond_dust")
    event.create("diamond_gear").texture("kubejs:item/materials/diamond/diamond_gear")
    event.create("diamond_plate").texture("kubejs:item/materials/diamond/diamond_plate")
    event.create("diamond_ring").texture("kubejs:item/materials/diamond/diamond_ring")
    event.create("diamond_rod").texture("kubejs:item/materials/diamond/diamond_rod")
    event.create("diamond_rotor").texture("kubejs:item/materials/diamond/diamond_rotor")
    event.create("diamond_wire").texture("kubejs:item/materials/diamond/diamond_wire")

    /*
    event.create("electrum_bolt").texture("kubejs:item/materials/electrum/electrum_bolt")
    event.create("electrum_curved_plate").texture("kubejs:item/materials/electrum/electrum_curved_plate")
    event.create("electrum_dust").texture("kubejs:item/materials/electrum/electrum_dust")
    event.create("electrum_gear").texture("kubejs:item/materials/electrum/electrum_gear")
    event.create("electrum_ingot").texture("kubejs:item/materials/electrum/electrum_ingot")
    event.create("electrum_nugget").texture("kubejs:item/materials/electrum/electrum_nugget")
    event.create("electrum_plate").texture("kubejs:item/materials/electrum/electrum_plate")
    event.create("electrum_ring").texture("kubejs:item/materials/electrum/electrum_ring")
    event.create("electrum_rod").texture("kubejs:item/materials/electrum/electrum_rod")
    event.create("electrum_rotor").texture("kubejs:item/materials/electrum/electrum_rotor")
    event.create("electrum_wire").texture("kubejs:item/materials/electrum/electrum_wire")
    */

    event.create("emerald_bolt").texture("kubejs:item/materials/emerald/emerald_bolt")
    event.create("emerald_curved_plate").texture("kubejs:item/materials/emerald/emerald_curved_plate")
    event.create("emerald_dust").texture("kubejs:item/materials/emerald/emerald_dust")
    event.create("emerald_gear").texture("kubejs:item/materials/emerald/emerald_gear")
    event.create("emerald_plate").texture("kubejs:item/materials/emerald/emerald_plate")
    event.create("emerald_ring").texture("kubejs:item/materials/emerald/emerald_ring")
    event.create("emerald_rod").texture("kubejs:item/materials/emerald/emerald_rod")
    event.create("emerald_rotor").texture("kubejs:item/materials/emerald/emerald_rotor")
    event.create("emerald_wire").texture("kubejs:item/materials/emerald/emerald_wire")
    
    event.create("gold_bolt").texture("kubejs:item/materials/gold/gold_bolt")
    event.create("gold_crushed_ore").displayName("Crushed Gold Ore").texture("kubejs:item/materials/gold/gold_crushed_ore")
    event.create("gold_curved_plate").texture("kubejs:item/materials/gold/gold_curved_plate")
    event.create("gold_dust").texture("kubejs:item/materials/gold/gold_dust")
    event.create("gold_gear").texture("kubejs:item/materials/gold/gold_gear")
    event.create("gold_plate").texture("kubejs:item/materials/gold/gold_plate")
    event.create("gold_ring").texture("kubejs:item/materials/gold/gold_ring")
    event.create("gold_rod").texture("kubejs:item/materials/gold/gold_rod")
    event.create("gold_rotor").texture("kubejs:item/materials/gold/gold_rotor")
    event.create("gold_wire").texture("kubejs:item/materials/gold/gold_wire")

    event.create("invar_bolt").texture("kubejs:item/materials/invar/invar_bolt")
    event.create("invar_curved_plate").texture("kubejs:item/materials/invar/invar_curved_plate")
    event.create("invar_dust").texture("kubejs:item/materials/invar/invar_dust")
    event.create("invar_gear").texture("kubejs:item/materials/invar/invar_gear")
    event.create("invar_ingot").texture("kubejs:item/materials/invar/invar_ingot")
    event.create("invar_nugget").texture("kubejs:item/materials/invar/invar_nugget")
    event.create("invar_plate").texture("kubejs:item/materials/invar/invar_plate")
    event.create("invar_ring").texture("kubejs:item/materials/invar/invar_ring")
    event.create("invar_rod").texture("kubejs:item/materials/invar/invar_rod")
    event.create("invar_rotor").texture("kubejs:item/materials/invar/invar_rotor")
    event.create("invar_wire").texture("kubejs:item/materials/invar/invar_wire")

    /*
    event.create("iridium_bolt").texture("kubejs:item/materials/iridium/iridium_bolt")
    event.create("iridium_crushed_ore").displayName("Crushed Iridium Ore").texture("kubejs:item/materials/iridium/iridium_crushed_ore")
    event.create("iridium_curved_plate").texture("kubejs:item/materials/iridium/iridium_curved_plate")
    event.create("iridium_dust").texture("kubejs:item/materials/iridium/iridium_dust")
    event.create("iridium_gear").texture("kubejs:item/materials/iridium/iridium_gear")
    event.create("iridium_ingot").texture("kubejs:item/materials/iridium/iridium_ingot")
    event.create("iridium_nugget").texture("kubejs:item/materials/iridium/iridium_nugget")
    event.create("iridium_plate").texture("kubejs:item/materials/iridium/iridium_plate")
    event.create("iridium_raw_material").displayName("Raw Iridium").texture("kubejs:item/materials/iridium/iridium_raw_material")
    event.create("iridium_ring").texture("kubejs:item/materials/iridium/iridium_ring")
    event.create("iridium_rod").texture("kubejs:item/materials/iridium/iridium_rod")
    event.create("iridium_rotor").texture("kubejs:item/materials/iridium/iridium_rotor")
    event.create("iridium_wire").texture("kubejs:item/materials/iridium/iridium_wire")
    */

    /*
    event.create("iridium_alloy_bolt").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_bolt")
    event.create("iridium_alloy_curved_plate").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_curved_plate")
    event.create("iridium_alloy_dust").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_dust")
    event.create("iridium_alloy_gear").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_gear")
    event.create("iridium_alloy_ingot").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_ingot")
    event.create("iridium_alloy_nugget").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_nugget")
    event.create("iridium_alloy_plate").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_plate")
    event.create("iridium_alloy_ring").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_ring")
    event.create("iridium_alloy_rod").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_rod")
    event.create("iridium_alloy_rotor").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_rotor")
    event.create("iridium_alloy_wire").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_wire")
    */

    event.create("iron_bolt").texture("kubejs:item/materials/iron/iron_bolt")
    event.create("iron_chunk").texture("kubejs:item/materials/iron/iron_chunk")
    event.create("iron_crushed_ore").displayName("Crushed Iron Ore").texture("kubejs:item/materials/iron/iron_crushed_ore")
    event.create("iron_curved_plate").texture("kubejs:item/materials/iron/iron_curved_plate")
    event.create("iron_dust").texture("kubejs:item/materials/iron/iron_dust")
    event.create("iron_gear").texture("kubejs:item/materials/iron/iron_gear")
    event.create("iron_plate").texture("kubejs:item/materials/iron/iron_plate")
    event.create("iron_ring").texture("kubejs:item/materials/iron/iron_ring")
    event.create("iron_rod").texture("kubejs:item/materials/iron/iron_rod")
    event.create("iron_rotor").texture("kubejs:item/materials/iron/iron_rotor")
    event.create("iron_wire").texture("kubejs:item/materials/iron/iron_wire")

    event.create("lapis_lazuli_bolt").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_bolt")
    event.create("lapis_lazuli_curved_plate").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_curved_plate")
    event.create("lapis_lazuli_dust").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_dust")
    event.create("lapis_lazuli_gear").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_gear")
    event.create("lapis_lazuli_plate").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_plate")
    event.create("lapis_lazuli_ring").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_ring")
    event.create("lapis_lazuli_rod").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_rod")
    event.create("lapis_lazuli_rotor").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_rotor")
    event.create("lapis_lazuli_wire").texture("kubejs:item/materials/lapis_lazuli/lapis_lazuli_wire")

    event.create("lead_bolt").texture("kubejs:item/materials/lead/lead_bolt")
    event.create("lead_crushed_ore").displayName("Crushed Lead Ore").texture("kubejs:item/materials/lead/lead_crushed_ore")
    event.create("lead_curved_plate").texture("kubejs:item/materials/lead/lead_curved_plate")
    event.create("lead_dust").texture("kubejs:item/materials/lead/lead_dust")
    event.create("lead_gear").texture("kubejs:item/materials/lead/lead_gear")
    event.create("lead_ingot").texture("kubejs:item/materials/lead/lead_ingot")
    event.create("lead_nugget").texture("kubejs:item/materials/lead/lead_nugget")
    event.create("lead_plate").texture("kubejs:item/materials/lead/lead_plate")
    event.create("lead_raw_material").displayName("Raw Lead").texture("kubejs:item/materials/lead/lead_raw_material")
    event.create("lead_ring").displayName("Raw Lead").texture("kubejs:item/materials/lead/lead_ring")
    event.create("lead_rod").texture("kubejs:item/materials/lead/lead_rod")
    event.create("lead_rotor").texture("kubejs:item/materials/lead/lead_rotor")
    event.create("lead_wire").texture("kubejs:item/materials/lead/lead_wire")

    event.create("nickel_bolt").texture("kubejs:item/materials/nickel/nickel_bolt")
    event.create("nickel_crushed_ore").displayName("Crushed Nickel Ore").texture("kubejs:item/materials/nickel/nickel_crushed_ore")
    event.create("nickel_curved_plate").texture("kubejs:item/materials/nickel/nickel_curved_plate")
    event.create("nickel_dust").texture("kubejs:item/materials/nickel/nickel_dust")
    event.create("nickel_gear").texture("kubejs:item/materials/nickel/nickel_gear")
    event.create("nickel_ingot").texture("kubejs:item/materials/nickel/nickel_ingot")
    event.create("nickel_nugget").texture("kubejs:item/materials/nickel/nickel_nugget")
    event.create("nickel_plate").texture("kubejs:item/materials/nickel/nickel_plate")
    event.create("nickel_raw_material").displayName("Raw Nickel").texture("kubejs:item/materials/nickel/nickel_raw_material")
    event.create("nickel_ring").texture("kubejs:item/materials/nickel/nickel_ring")
    event.create("nickel_rod").texture("kubejs:item/materials/nickel/nickel_rod")
    event.create("nickel_rotor").texture("kubejs:item/materials/nickel/nickel_rotor")
    event.create("nickel_wire").texture("kubejs:item/materials/nickel/nickel_wire")

    /*
    event.create("platinum_bolt").texture("kubejs:item/materials/platinum/platinum_bolt")
    event.create("platinum_crushed_ore").displayName("Crushed Platinum Ore").texture("kubejs:item/materials/platinum/platinum_crushed_ore")
    event.create("platinum_curved_plate").texture("kubejs:item/materials/platinum/platinum_curved_plate")
    event.create("platinum_dust").texture("kubejs:item/materials/platinum/platinum_dust")
    event.create("platinum_gear").texture("kubejs:item/materials/platinum/platinum_gear")
    event.create("platinum_ingot").texture("kubejs:item/materials/platinum/platinum_ingot")
    event.create("platinum_nugget").texture("kubejs:item/materials/platinum/platinum_nugget")
    event.create("platinum_plate").texture("kubejs:item/materials/platinum/platinum_plate")
    event.create("platinum_raw_material").displayName("Raw Platinum").texture("kubejs:item/materials/platinum/platinum_raw_material")
    event.create("platinum_ring").texture("kubejs:item/materials/platinum/platinum_ring")
    event.create("platinum_rod").texture("kubejs:item/materials/platinum/platinum_rod")
    event.create("platinum_rotor").texture("kubejs:item/materials/platinum/platinum_rotor")
    event.create("platinum_wire").texture("kubejs:item/materials/platinum/platinum_wire")
    */

    event.create("steel_bolt").texture("kubejs:item/materials/steel/steel_bolt")
    event.create("steel_curved_plate").texture("kubejs:item/materials/steel/steel_curved_plate")
    event.create("steel_dust").texture("kubejs:item/materials/steel/steel_dust")
    event.create("steel_gear").texture("kubejs:item/materials/steel/steel_gear")
    event.create("steel_ingot").texture("kubejs:item/materials/steel/steel_ingot")
    event.create("steel_nugget").texture("kubejs:item/materials/steel/steel_nugget")
    event.create("steel_plate").texture("kubejs:item/materials/steel/steel_plate")
    event.create("steel_ring").texture("kubejs:item/materials/steel/steel_ring")
    event.create("steel_rod").texture("kubejs:item/materials/steel/steel_rod")
    event.create("steel_rotor").texture("kubejs:item/materials/steel/steel_rotor")
    event.create("steel_wire").texture("kubejs:item/materials/steel/steel_wire")

    event.create("tin_bolt").texture("kubejs:item/materials/tin/tin_bolt")
    event.create("tin_chunk").texture("kubejs:item/materials/tin/tin_chunk")
    event.create("tin_crushed_ore").displayName("Crushed Tin Ore").texture("kubejs:item/materials/tin/tin_crushed_ore")
    event.create("tin_curved_plate").texture("kubejs:item/materials/tin/tin_curved_plate")
    event.create("tin_dust").texture("kubejs:item/materials/tin/tin_dust")
    event.create("tin_gear").texture("kubejs:item/materials/tin/tin_gear")
    event.create("tin_ingot").texture("kubejs:item/materials/tin/tin_ingot")
    event.create("tin_nugget").texture("kubejs:item/materials/tin/tin_nugget")
    event.create("tin_plate").texture("kubejs:item/materials/tin/tin_plate")
    event.create("tin_raw_material").displayName("Raw Tin").texture("kubejs:item/materials/tin/tin_raw_material")
    event.create("tin_ring").texture("kubejs:item/materials/tin/tin_ring")
    event.create("tin_rod").texture("kubejs:item/materials/tin/tin_rod")
    event.create("tin_rotor").texture("kubejs:item/materials/tin/tin_rotor")
    event.create("tin_wire").texture("kubejs:item/materials/tin/tin_wire")

    /*
    event.create("titanium_bolt").texture("kubejs:item/materials/titanium/titanium_bolt")
    event.create("titanium_crushed_ore").displayName("Crushed Titanium Ore").texture("kubejs:item/materials/titanium/titanium_crushed_ore")
    event.create("titanium_curved_plate").texture("kubejs:item/materials/titanium/titanium_curved_plate")
    event.create("titanium_dust").texture("kubejs:item/materials/titanium/titanium_dust")
    event.create("titanium_gear").texture("kubejs:item/materials/titanium/titanium_gear")
    event.create("titanium_ingot").texture("kubejs:item/materials/titanium/titanium_ingot")
    event.create("titanium_nugget").texture("kubejs:item/materials/titanium/titanium_nugget")
    event.create("titanium_plate").texture("kubejs:item/materials/titanium/titanium_plate")
    event.create("titanium_raw_material").displayName("Raw Titanium").texture("kubejs:item/materials/titanium/titanium_raw_material")
    event.create("titanium_ring").texture("kubejs:item/materials/titanium/titanium_ring")
    event.create("titanium_rod").texture("kubejs:item/materials/titanium/titanium_rod")
    event.create("titanium_rotor").texture("kubejs:item/materials/titanium/titanium_rotor")
    event.create("titanium_wire").texture("kubejs:item/materials/titanium/titanium_wire")
    */

    event.create("zinc_bolt").texture("kubejs:item/materials/zinc/zinc_bolt")
    event.create("zinc_crushed_ore").displayName("Crushed Zinc Ore").texture("kubejs:item/materials/zinc/zinc_crushed_ore")
    event.create("zinc_curved_plate").texture("kubejs:item/materials/zinc/zinc_curved_plate")
    event.create("zinc_dust").texture("kubejs:item/materials/zinc/zinc_dust")
    event.create("zinc_gear").texture("kubejs:item/materials/zinc/zinc_gear")
    event.create("zinc_ingot").texture("kubejs:item/materials/zinc/zinc_ingot")
    event.create("zinc_nugget").texture("kubejs:item/materials/zinc/zinc_nugget")
    event.create("zinc_plate").texture("kubejs:item/materials/zinc/zinc_plate")
    event.create("zinc_raw_material").displayName("Raw Zinc").texture("kubejs:item/materials/zinc/zinc_raw_material")
    event.create("zinc_ring").texture("kubejs:item/materials/zinc/zinc_ring")
    event.create("zinc_rod").texture("kubejs:item/materials/zinc/zinc_rod")
    event.create("zinc_rotor").texture("kubejs:item/materials/zinc/zinc_rotor")
    event.create("zinc_wire").texture("kubejs:item/materials/zinc/zinc_wire")


    event.create("drawer_template_1x1").displayName("1x1 Drawer Template").texture("kubejs:item/itemfilters/drawer_template_1x1")
    event.create("drawer_template_1x2").displayName("1x2 Drawer Template").texture("kubejs:item/itemfilters/drawer_template_1x2")
    event.create("drawer_template_2x2").displayName("2x2 Drawer Template").texture("kubejs:item/itemfilters/drawer_template_2x2")
    event.create("block_template").texture("kubejs:item/itemfilters/block_template")
    event.create("boat_template").texture("kubejs:item/itemfilters/boat_template")
    event.create("button_template").texture("kubejs:item/itemfilters/button_template")
    event.create("carpet_template").texture("kubejs:item/itemfilters/carpet_template")
    event.create("color_template").texture("kubejs:item/itemfilters/color_template")
    event.create("door_template").texture("kubejs:item/itemfilters/door_template")
    event.create("fence_gate_template").texture("kubejs:item/itemfilters/fence_gate_template")
    event.create("fence_template").texture("kubejs:item/itemfilters/fence_template")
    event.create("glass_pane_template").texture("kubejs:item/itemfilters/glass_pane_template")
    event.create("log_template").texture("kubejs:item/itemfilters/log_template")
    event.create("pressure_plate_template").texture("kubejs:item/itemfilters/pressure_plate_template")
    event.create("sign_template").texture("kubejs:item/itemfilters/sign_template")
    event.create("slab_template").texture("kubejs:item/itemfilters/slab_template")
    event.create("stairs_template").texture("kubejs:item/itemfilters/stairs_template")
    event.create("trapdoor_template").texture("kubejs:item/itemfilters/trapdoor_template")
    event.create("wall_template").texture("kubejs:item/itemfilters/wall_template")
    event.create("waxing_template").texture("kubejs:item/itemfilters/waxing_template")


    //tier 1
    event.create("iron_hammer").texture("kubejs:item/ee/iron_hammer").maxDamage(256)

    //tier 2
    event.create("steel_hammer").texture("kubejs:item/ee/steel_hammer").maxDamage(768)
    
    event.create("coal_coke").texture("kubejs:item/materials/coal_coke/coal_coke").burnTime(3200)
    event.create("coal_coke_dust").texture("kubejs:item/materials/coal_coke/coal_coke_dust")

    //event.create("aluminum_drill_head").texture("kubejs:item/mi/drill/aluminum_drill_head")
    //event.create("aluminum_drill").texture("kubejs:item/mi/drill/aluminum_drill")
    event.create("bronze_drill_head").texture("kubejs:item/mi/drill/bronze_drill_head")
    event.create("bronze_drill").texture("kubejs:item/mi/drill/bronze_drill")
    event.create("copper_drill_head").texture("kubejs:item/mi/drill/copper_drill_head")
    event.create("copper_drill").texture("kubejs:item/mi/drill/copper_drill")
    event.create("gold_drill_head").texture("kubejs:item/mi/drill/gold_drill_head")
    event.create("gold_drill").texture("kubejs:item/mi/drill/gold_drill")
    event.create("steel_drill_head").texture("kubejs:item/mi/drill/steel_drill_head")
    event.create("steel_drill").texture("kubejs:item/mi/drill/steel_drill")
    //event.create("titanium_drill_head").texture("kubejs:item/mi/drill/titanium_drill_head")
    //event.create("titanium_drill").texture("kubejs:item/mi/drill/titanium_drill")

    event.create("motor").texture("kubejs:item/mi/motor")
    event.create("capacitor").texture("kubejs:item/mi/capacitor")
    event.create("resistor").texture("kubejs:item/mi/resistor")
    event.create("inductor").texture("kubejs:item/mi/inductor")
    event.create("analog_circuit").displayName("Circuit").texture("kubejs:item/create/analog_circuit")
})  