StartupEvents.registry("item", event => {
    //materials
    event.create("advanced_alloy_dust").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_dust")
    event.create("advanced_alloy_gear").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_gear")
    event.create("advanced_alloy_ingot").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_ingot")
    event.create("advanced_alloy_nugget").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_nugget")
    event.create("advanced_alloy_plate").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_plate")
    event.create("advanced_alloy_rod").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_rod")
    event.create("advanced_alloy_wire").texture("kubejs:item/materials/advanced_alloy/advanced_alloy_wire")

    event.create("aluminum_crushed_ore").displayName("Crushed Aluminum Ore").texture("kubejs:item/materials/aluminum/aluminum_crushed_ore")
    event.create("aluminum_dust").texture("kubejs:item/materials/aluminum/aluminum_dust")
    event.create("aluminum_gear").texture("kubejs:item/materials/aluminum/aluminum_gear")
    event.create("aluminum_ingot").texture("kubejs:item/materials/aluminum/aluminum_ingot")
    event.create("aluminum_nugget").texture("kubejs:item/materials/aluminum/aluminum_nugget")
    event.create("aluminum_plate").texture("kubejs:item/materials/aluminum/aluminum_plate")
    event.create("aluminum_raw_material").displayName("Raw Aluminum").texture("kubejs:item/materials/aluminum/aluminum_raw_material")
    event.create("aluminum_rod").texture("kubejs:item/materials/aluminum/aluminum_rod")
    event.create("aluminum_wire").texture("kubejs:item/materials/aluminum/aluminum_wire")

    event.create("bismuth_crushed_ore").displayName("Crushed Bismuth Ore").texture("kubejs:item/materials/bismuth/bismuth_crushed_ore")
    event.create("bismuth_dust").texture("kubejs:item/materials/bismuth/bismuth_dust")
    event.create("bismuth_gear").texture("kubejs:item/materials/bismuth/bismuth_gear")
    event.create("bismuth_ingot").texture("kubejs:item/materials/bismuth/bismuth_ingot")
    event.create("bismuth_nugget").texture("kubejs:item/materials/bismuth/bismuth_nugget")
    event.create("bismuth_plate").texture("kubejs:item/materials/bismuth/bismuth_plate")
    event.create("bismuth_raw_material").displayName("Raw Bismuth").texture("kubejs:item/materials/bismuth/bismuth_raw_material")
    event.create("bismuth_rod").texture("kubejs:item/materials/bismuth/bismuth_rod")
    event.create("bismuth_wire").texture("kubejs:item/materials/bismuth/bismuth_wire")

    event.create("brass_dust").texture("kubejs:item/materials/brass/brass_dust")
    event.create("brass_gear").texture("kubejs:item/materials/brass/brass_gear")
    event.create("brass_ingot").texture("kubejs:item/materials/brass/brass_ingot")
    event.create("brass_nugget").texture("kubejs:item/materials/brass/brass_nugget")
    event.create("brass_plate").texture("kubejs:item/materials/brass/brass_plate")
    event.create("brass_rod").texture("kubejs:item/materials/brass/brass_rod")
    event.create("brass_wire").texture("kubejs:item/materials/brass/brass_wire")

    event.create("bronze_chunk").texture("kubejs:item/materials/bronze/bronze_chunk")
    event.create("bronze_dust").texture("kubejs:item/materials/bronze/bronze_dust")
    event.create("bronze_gear").texture("kubejs:item/materials/bronze/bronze_gear")
    event.create("bronze_ingot").texture("kubejs:item/materials/bronze/bronze_ingot")
    event.create("bronze_nugget").texture("kubejs:item/materials/bronze/bronze_nugget")
    event.create("bronze_plate").texture("kubejs:item/materials/bronze/bronze_plate")
    event.create("bronze_rod").texture("kubejs:item/materials/bronze/bronze_rod")
    event.create("bronze_wire").texture("kubejs:item/materials/bronze/bronze_wire")

    event.create("cobalt_crushed_ore").displayName("Crushed Cobalt Ore").texture("kubejs:item/materials/cobalt/cobalt_crushed_ore")
    event.create("cobalt_dust").texture("kubejs:item/materials/cobalt/cobalt_dust")
    event.create("cobalt_gear").texture("kubejs:item/materials/cobalt/cobalt_gear")
    event.create("cobalt_ingot").texture("kubejs:item/materials/cobalt/cobalt_ingot")
    event.create("cobalt_nugget").texture("kubejs:item/materials/cobalt/cobalt_nugget")
    event.create("cobalt_plate").texture("kubejs:item/materials/cobalt/cobalt_plate")
    event.create("cobalt_raw_material").displayName("Raw Cobalt").texture("kubejs:item/materials/cobalt/cobalt_raw_material")
    event.create("cobalt_rod").texture("kubejs:item/materials/cobalt/cobalt_rod")
    event.create("cobalt_wire").texture("kubejs:item/materials/cobalt/cobalt_wire")

    event.create("constantan_dust").texture("kubejs:item/materials/constantan/constantan_dust")
    event.create("constantan_gear").texture("kubejs:item/materials/constantan/constantan_gear")
    event.create("constantan_ingot").texture("kubejs:item/materials/constantan/constantan_ingot")
    event.create("constantan_nugget").texture("kubejs:item/materials/constantan/constantan_nugget")
    event.create("constantan_plate").texture("kubejs:item/materials/constantan/constantan_plate")
    event.create("constantan_rod").texture("kubejs:item/materials/constantan/constantan_rod")
    event.create("constantan_wire").texture("kubejs:item/materials/constantan/constantan_wire")

    event.create("copper_chunk").texture("kubejs:item/materials/copper/copper_chunk")
    event.create("copper_crushed_ore").displayName("Crushed Copper Ore").texture("kubejs:item/materials/copper/copper_crushed_ore")
    event.create("copper_dust").texture("kubejs:item/materials/copper/copper_dust")
    event.create("copper_gear").texture("kubejs:item/materials/copper/copper_gear")
    event.create("copper_plate").texture("kubejs:item/materials/copper/copper_plate")
    event.create("copper_rod").texture("kubejs:item/materials/copper/copper_rod")
    event.create("copper_wire").texture("kubejs:item/materials/copper/copper_wire")

    event.create("diamond_dust").texture("kubejs:item/materials/diamond/diamond_dust")
    event.create("diamond_gear").texture("kubejs:item/materials/diamond/diamond_gear")
    event.create("diamond_plate").texture("kubejs:item/materials/diamond/diamond_plate")
    event.create("diamond_rod").texture("kubejs:item/materials/diamond/diamond_rod")
    event.create("diamond_wire").texture("kubejs:item/materials/diamond/diamond_wire")

    event.create("electrum_dust").texture("kubejs:item/materials/electrum/electrum_dust")
    event.create("electrum_gear").texture("kubejs:item/materials/electrum/electrum_gear")
    event.create("electrum_ingot").texture("kubejs:item/materials/electrum/electrum_ingot")
    event.create("electrum_nugget").texture("kubejs:item/materials/electrum/electrum_nugget")
    event.create("electrum_plate").texture("kubejs:item/materials/electrum/electrum_plate")
    event.create("electrum_rod").texture("kubejs:item/materials/electrum/electrum_rod")
    event.create("electrum_wire").texture("kubejs:item/materials/electrum/electrum_wire")

    event.create("emerald_dust").texture("kubejs:item/materials/emerald/emerald_dust")
    event.create("emerald_gear").texture("kubejs:item/materials/emerald/emerald_gear")
    event.create("emerald_plate").texture("kubejs:item/materials/emerald/emerald_plate")
    event.create("emerald_rod").texture("kubejs:item/materials/emerald/emerald_rod")
    event.create("emerald_wire").texture("kubejs:item/materials/emerald/emerald_wire")

    event.create("enderium_dust").texture("kubejs:item/materials/enderium/enderium_dust")
    event.create("enderium_gear").texture("kubejs:item/materials/enderium/enderium_gear")
    event.create("enderium_ingot").texture("kubejs:item/materials/enderium/enderium_ingot")
    event.create("enderium_nugget").texture("kubejs:item/materials/enderium/enderium_nugget")
    event.create("enderium_plate").texture("kubejs:item/materials/enderium/enderium_plate")
    event.create("enderium_rod").texture("kubejs:item/materials/enderium/enderium_rod")
    event.create("enderium_wire").texture("kubejs:item/materials/enderium/enderium_wire")
    
    event.create("gold_crushed_ore").displayName("Crushed Gold Ore").texture("kubejs:item/materials/gold/gold_crushed_ore")
    event.create("gold_dust").texture("kubejs:item/materials/gold/gold_dust")
    event.create("gold_gear").texture("kubejs:item/materials/gold/gold_gear")
    event.create("gold_plate").texture("kubejs:item/materials/gold/gold_plate")
    event.create("gold_rod").texture("kubejs:item/materials/gold/gold_rod")
    event.create("gold_wire").texture("kubejs:item/materials/gold/gold_wire")

    event.create("invar_dust").texture("kubejs:item/materials/invar/invar_dust")
    event.create("invar_gear").texture("kubejs:item/materials/invar/invar_gear")
    event.create("invar_ingot").texture("kubejs:item/materials/invar/invar_ingot")
    event.create("invar_nugget").texture("kubejs:item/materials/invar/invar_nugget")
    event.create("invar_plate").texture("kubejs:item/materials/invar/invar_plate")
    event.create("invar_rod").texture("kubejs:item/materials/invar/invar_rod")
    event.create("invar_wire").texture("kubejs:item/materials/invar/invar_wire")

    event.create("iridium_crushed_ore").displayName("Crushed Iridium Ore").texture("kubejs:item/materials/iridium/iridium_crushed_ore")
    event.create("iridium_dust").texture("kubejs:item/materials/iridium/iridium_dust")
    event.create("iridium_gear").texture("kubejs:item/materials/iridium/iridium_gear")
    event.create("iridium_ingot").texture("kubejs:item/materials/iridium/iridium_ingot")
    event.create("iridium_nugget").texture("kubejs:item/materials/iridium/iridium_nugget")
    event.create("iridium_plate").texture("kubejs:item/materials/iridium/iridium_plate")
    event.create("iridium_raw_material").displayName("Raw Iridium").texture("kubejs:item/materials/iridium/iridium_raw_material")
    event.create("iridium_rod").texture("kubejs:item/materials/iridium/iridium_rod")
    event.create("iridium_wire").texture("kubejs:item/materials/iridium/iridium_wire")

    event.create("iridium_alloy_dust").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_dust")
    event.create("iridium_alloy_gear").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_gear")
    event.create("iridium_alloy_ingot").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_ingot")
    event.create("iridium_alloy_nugget").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_nugget")
    event.create("iridium_alloy_plate").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_plate")
    event.create("iridium_alloy_rod").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_rod")
    event.create("iridium_alloy_wire").texture("kubejs:item/materials/iridium_alloy/iridium_alloy_wire")

    event.create("iron_chunk").texture("kubejs:item/materials/iron/iron_chunk")
    event.create("iron_crushed_ore").displayName("Crushed Iron Ore").texture("kubejs:item/materials/iron/iron_crushed_ore")
    event.create("iron_dust").texture("kubejs:item/materials/iron/iron_dust")
    event.create("iron_gear").texture("kubejs:item/materials/iron/iron_gear")
    event.create("iron_plate").texture("kubejs:item/materials/iron/iron_plate")
    event.create("iron_rod").texture("kubejs:item/materials/iron/iron_rod")
    event.create("iron_wire").texture("kubejs:item/materials/iron/iron_wire")

    event.create("lapiz_lazuli_dust").texture("kubejs:item/materials/lapiz_lazuli/lapiz_lazuli_dust")
    event.create("lapiz_lazuli_gear").texture("kubejs:item/materials/lapiz_lazuli/lapiz_lazuli_gear")
    event.create("lapiz_lazuli_plate").texture("kubejs:item/materials/lapiz_lazuli/lapiz_lazuli_plate")
    event.create("lapiz_lazuli_rod").texture("kubejs:item/materials/lapiz_lazuli/lapiz_lazuli_rod")
    event.create("lapiz_lazuli_wire").texture("kubejs:item/materials/lapiz_lazuli/lapiz_lazuli_wire")

    event.create("lead_crushed_ore").displayName("Crushed Lead Ore").texture("kubejs:item/materials/lead/lead_crushed_ore")
    event.create("lead_dust").texture("kubejs:item/materials/lead/lead_dust")
    event.create("lead_gear").texture("kubejs:item/materials/lead/lead_gear")
    event.create("lead_ingot").texture("kubejs:item/materials/lead/lead_ingot")
    event.create("lead_nugget").texture("kubejs:item/materials/lead/lead_nugget")
    event.create("lead_plate").texture("kubejs:item/materials/lead/lead_plate")
    event.create("lead_raw_material").displayName("Raw Lead").texture("kubejs:item/materials/lead/lead_raw_material")
    event.create("lead_rod").texture("kubejs:item/materials/lead/lead_rod")
    event.create("lead_wire").texture("kubejs:item/materials/lead/lead_wire")

    event.create("lumium_dust").texture("kubejs:item/materials/lumium/lumium_dust")
    event.create("lumium_gear").texture("kubejs:item/materials/lumium/lumium_gear")
    event.create("lumium_ingot").texture("kubejs:item/materials/lumium/lumium_ingot")
    event.create("lumium_nugget").texture("kubejs:item/materials/lumium/lumium_nugget")
    event.create("lumium_plate").texture("kubejs:item/materials/lumium/lumium_plate")
    event.create("lumium_rod").texture("kubejs:item/materials/lumium/lumium_rod")
    event.create("lumium_wire").texture("kubejs:item/materials/lumium/lumium_wire")

    event.create("magnesium_crushed_ore").displayName("Crushed Magnesium Ore").texture("kubejs:item/materials/magnesium/magnesium_crushed_ore")
    event.create("magnesium_dust").texture("kubejs:item/materials/magnesium/magnesium_dust")
    event.create("magnesium_gear").texture("kubejs:item/materials/magnesium/magnesium_gear")
    event.create("magnesium_ingot").texture("kubejs:item/materials/magnesium/magnesium_ingot")
    event.create("magnesium_nugget").texture("kubejs:item/materials/magnesium/magnesium_nugget")
    event.create("magnesium_plate").texture("kubejs:item/materials/magnesium/magnesium_plate")
    event.create("magnesium_raw_material").displayName("Raw Magnesium").texture("kubejs:item/materials/magnesium/magnesium_raw_material")
    event.create("magnesium_rod").texture("kubejs:item/materials/magnesium/magnesium_rod")
    event.create("magnesium_wire").texture("kubejs:item/materials/magnesium/magnesium_wire")

    event.create("nickel_crushed_ore").displayName("Crushed Nickel Ore").texture("kubejs:item/materials/nickel/nickel_crushed_ore")
    event.create("nickel_dust").texture("kubejs:item/materials/nickel/nickel_dust")
    event.create("nickel_gear").texture("kubejs:item/materials/nickel/nickel_gear")
    event.create("nickel_ingot").texture("kubejs:item/materials/nickel/nickel_ingot")
    event.create("nickel_nugget").texture("kubejs:item/materials/nickel/nickel_nugget")
    event.create("nickel_plate").texture("kubejs:item/materials/nickel/nickel_plate")
    event.create("nickel_raw_material").displayName("Raw Nickel").texture("kubejs:item/materials/nickel/nickel_raw_material")
    event.create("nickel_rod").texture("kubejs:item/materials/nickel/nickel_rod")
    event.create("nickel_wire").texture("kubejs:item/materials/nickel/nickel_wire")

    event.create("osmium_crushed_ore").displayName("Crushed Osmium Ore").texture("kubejs:item/materials/osmium/osmium_crushed_ore")
    event.create("osmium_dust").texture("kubejs:item/materials/osmium/osmium_dust")
    event.create("osmium_gear").texture("kubejs:item/materials/osmium/osmium_gear")
    event.create("osmium_ingot").texture("kubejs:item/materials/osmium/osmium_ingot")
    event.create("osmium_nugget").texture("kubejs:item/materials/osmium/osmium_nugget")
    event.create("osmium_plate").texture("kubejs:item/materials/osmium/osmium_plate")
    event.create("osmium_raw_material").displayName("Raw Osmium").texture("kubejs:item/materials/osmium/osmium_raw_material")
    event.create("osmium_rod").texture("kubejs:item/materials/osmium/osmium_rod")
    event.create("osmium_wire").texture("kubejs:item/materials/osmium/osmium_wire")

    event.create("platinum_crushed_ore").displayName("Crushed Platinum Ore").texture("kubejs:item/materials/platinum/platinum_crushed_ore")
    event.create("platinum_dust").texture("kubejs:item/materials/platinum/platinum_dust")
    event.create("platinum_gear").texture("kubejs:item/materials/platinum/platinum_gear")
    event.create("platinum_ingot").texture("kubejs:item/materials/platinum/platinum_ingot")
    event.create("platinum_nugget").texture("kubejs:item/materials/platinum/platinum_nugget")
    event.create("platinum_plate").texture("kubejs:item/materials/platinum/platinum_plate")
    event.create("platinum_raw_material").displayName("Raw Platinum").texture("kubejs:item/materials/platinum/platinum_raw_material")
    event.create("platinum_rod").texture("kubejs:item/materials/platinum/platinum_rod")
    event.create("platinum_wire").texture("kubejs:item/materials/platinum/platinum_wire")

    event.create("refined_glowstone_dust").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_dust")
    event.create("refined_glowstone_gear").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_gear")
    event.create("refined_glowstone_ingot").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_ingot")
    event.create("refined_glowstone_nugget").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_nugget")
    event.create("refined_glowstone_plate").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_plate")
    event.create("refined_glowstone_rod").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_rod")
    event.create("refined_glowstone_wire").texture("kubejs:item/materials/refined_glowstone/refined_glowstone_wire")

    event.create("refined_obsidian_dust").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_dust")
    event.create("refined_obsidian_gear").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_gear")
    event.create("refined_obsidian_ingot").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_ingot")
    event.create("refined_obsidian_nugget").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_nugget")
    event.create("refined_obsidian_plate").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_plate")
    event.create("refined_obsidian_rod").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_rod")
    event.create("refined_obsidian_wire").texture("kubejs:item/materials/refined_obsidian/refined_obsidian_wire")

    event.create("signalum_dust").texture("kubejs:item/materials/signalum/signalum_dust")
    event.create("signalum_gear").texture("kubejs:item/materials/signalum/signalum_gear")
    event.create("signalum_ingot").texture("kubejs:item/materials/signalum/signalum_ingot")
    event.create("signalum_nugget").texture("kubejs:item/materials/signalum/signalum_nugget")
    event.create("signalum_plate").texture("kubejs:item/materials/signalum/signalum_plate")
    event.create("signalum_rod").texture("kubejs:item/materials/signalum/signalum_rod")
    event.create("signalum_wire").texture("kubejs:item/materials/signalum/signalum_wire")

    event.create("silver_crushed_ore").displayName("Crushed Silver Ore").texture("kubejs:item/materials/silver/silver_crushed_ore")
    event.create("silver_dust").texture("kubejs:item/materials/silver/silver_dust")
    event.create("silver_gear").texture("kubejs:item/materials/silver/silver_gear")
    event.create("silver_ingot").texture("kubejs:item/materials/silver/silver_ingot")
    event.create("silver_nugget").texture("kubejs:item/materials/silver/silver_nugget")
    event.create("silver_plate").texture("kubejs:item/materials/silver/silver_plate")
    event.create("silver_raw_material").displayName("Raw Silver").texture("kubejs:item/materials/silver/silver_raw_material")
    event.create("silver_rod").texture("kubejs:item/materials/silver/silver_rod")
    event.create("silver_wire").texture("kubejs:item/materials/silver/silver_wire")

    event.create("steel_dust").texture("kubejs:item/materials/steel/steel_dust")
    event.create("steel_gear").texture("kubejs:item/materials/steel/steel_gear")
    event.create("steel_ingot").texture("kubejs:item/materials/steel/steel_ingot")
    event.create("steel_nugget").texture("kubejs:item/materials/steel/steel_nugget")
    event.create("steel_plate").texture("kubejs:item/materials/steel/steel_plate")
    event.create("steel_rod").texture("kubejs:item/materials/steel/steel_rod")
    event.create("steel_wire").texture("kubejs:item/materials/steel/steel_wire")

    event.create("tin_chunk").texture("kubejs:item/materials/tin/tin_chunk")
    event.create("tin_crushed_ore").displayName("Crushed Tin Ore").texture("kubejs:item/materials/tin/tin_crushed_ore")
    event.create("tin_dust").texture("kubejs:item/materials/tin/tin_dust")
    event.create("tin_gear").texture("kubejs:item/materials/tin/tin_gear")
    event.create("tin_ingot").texture("kubejs:item/materials/tin/tin_ingot")
    event.create("tin_nugget").texture("kubejs:item/materials/tin/tin_nugget")
    event.create("tin_plate").texture("kubejs:item/materials/tin/tin_plate")
    event.create("tin_raw_material").displayName("Raw Tin").texture("kubejs:item/materials/tin/tin_raw_material")
    event.create("tin_rod").texture("kubejs:item/materials/tin/tin_rod")
    event.create("tin_wire").texture("kubejs:item/materials/tin/tin_wire")

    event.create("titanium_crushed_ore").displayName("Crushed Titanium Ore").texture("kubejs:item/materials/titanium/titanium_crushed_ore")
    event.create("titanium_dust").texture("kubejs:item/materials/titanium/titanium_dust")
    event.create("titanium_gear").texture("kubejs:item/materials/titanium/titanium_gear")
    event.create("titanium_ingot").texture("kubejs:item/materials/titanium/titanium_ingot")
    event.create("titanium_nugget").texture("kubejs:item/materials/titanium/titanium_nugget")
    event.create("titanium_plate").texture("kubejs:item/materials/titanium/titanium_plate")
    event.create("titanium_raw_material").displayName("Raw Titanium").texture("kubejs:item/materials/titanium/titanium_raw_material")
    event.create("titanium_rod").texture("kubejs:item/materials/titanium/titanium_rod")
    event.create("titanium_wire").texture("kubejs:item/materials/titanium/titanium_wire")

    event.create("tungsten_crushed_ore").displayName("Crushed Tungsten Ore").texture("kubejs:item/materials/tungsten/tungsten_crushed_ore")
    event.create("tungsten_dust").texture("kubejs:item/materials/tungsten/tungsten_dust")
    event.create("tungsten_gear").texture("kubejs:item/materials/tungsten/tungsten_gear")
    event.create("tungsten_ingot").texture("kubejs:item/materials/tungsten/tungsten_ingot")
    event.create("tungsten_nugget").texture("kubejs:item/materials/tungsten/tungsten_nugget")
    event.create("tungsten_plate").texture("kubejs:item/materials/tungsten/tungsten_plate")
    event.create("tungsten_raw_material").displayName("Raw Tungsten").texture("kubejs:item/materials/tungsten/tungsten_raw_material")
    event.create("tungsten_rod").texture("kubejs:item/materials/tungsten/tungsten_rod")
    event.create("tungsten_wire").texture("kubejs:item/materials/tungsten/tungsten_wire")

    event.create("zinc_crushed_ore").displayName("Crushed Zinc Ore").texture("kubejs:item/materials/zinc/zinc_crushed_ore")
    event.create("zinc_dust").texture("kubejs:item/materials/zinc/zinc_dust")
    event.create("zinc_gear").texture("kubejs:item/materials/zinc/zinc_gear")
    event.create("zinc_ingot").texture("kubejs:item/materials/zinc/zinc_ingot")
    event.create("zinc_nugget").texture("kubejs:item/materials/zinc/zinc_nugget")
    event.create("zinc_plate").texture("kubejs:item/materials/zinc/zinc_plate")
    event.create("zinc_raw_material").displayName("Raw Zinc").texture("kubejs:item/materials/zinc/zinc_raw_material")
    event.create("zinc_rod").texture("kubejs:item/materials/zinc/zinc_rod")
    event.create("zinc_wire").texture("kubejs:item/materials/zinc/zinc_wire")


    //tier 1
    event.create("hammer").texture("kubejs:item/ee/hammer").maxDamage(64)
})  