JEIEvents.hideItems(event => {
    event.hide("kubejs:inventory_furnace_tier_3")
    event.hide("kubejs:inventory_furnace_tier_4")
    event.hide("kubejs:inventory_macerator_tier_3")
    event.hide("kubejs:inventory_macerator_tier_4")
    event.hide("kubejs:inventory_compressor_tier_3")
    event.hide("kubejs:inventory_compressor_tier_4")
    event.hide("kubejs:inventory_cutting_machine_tier_3")
    event.hide("kubejs:inventory_cutting_machine_tier_4")
    event.hide("kubejs:inventory_packer_tier_3")
    event.hide("kubejs:inventory_packer_tier_4")
    event.hide("kubejs:inventory_unpacker_tier_3")
    event.hide("kubejs:inventory_unpacker_tier_4")
    event.hide("kubejs:inventory_wiremill_tier_2")
    event.hide("kubejs:inventory_wiremill_tier_3")
    event.hide("kubejs:inventory_coke_oven_tier_3")
    event.hide("kubejs:inventory_coke_oven_tier_4")
    event.hide("kubejs:inventory_blast_furnace_tier_3")
    event.hide("kubejs:inventory_blast_furnace_tier_4")
    event.hide("kubejs:inventory_mixer_tier_2")
    event.hide("kubejs:inventory_mixer_tier_3")
    event.hide("kubejs:inventory_quarry_tier_2")
    event.hide("kubejs:inventory_quarry_tier_3")
    event.hide("kubejs:inventory_assembler_tier_2")
    event.hide("kubejs:inventory_assembler_tier_3")

    event.hide("kubejs:aluminum_ore")
    event.hide("kubejs:aluminum_ore_deepslate")
    event.hide("kubejs:cobalt_ore")
    event.hide("kubejs:iridium_ore")
    event.hide("kubejs:iridium_ore_deepslate")
    event.hide("kubejs:platinum_ore")
    event.hide("kubejs:platinum_ore_deepslate")
    event.hide("kubejs:titanium_ore")

    event.hide("kubejs:copper_crushed_ore")
    event.hide("kubejs:gold_crushed_ore")
    event.hide("kubejs:iron_crushed_ore")
    event.hide("kubejs:lead_crushed_ore")
    event.hide("kubejs:nickel_crushed_ore")
    event.hide("kubejs:tin_crushed_ore")
    event.hide("kubejs:zinc_crushed_ore")

    event.hide(/itemfilters:.*/)
})