
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1046852
	#The name of the modpack
	modpackName = "Factorized Inventory"
	#The version of the modpack
	modpackVersion = "0.1.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

