addAssemblerRecipe("kubejs:copper_drill_head", ["2x kubejs:copper_curved_plate", "2x kubejs:copper_rod", "kubejs:copper_gear", "kubejs:copper_plate"])
addAssemblerRecipe("kubejs:bronze_drill_head", ["2x kubejs:bronze_curved_plate", "2x kubejs:bronze_rod", "kubejs:bronze_gear", "kubejs:bronze_plate"])
addAssemblerRecipe("kubejs:steel_drill_head", ["2x kubejs:steel_curved_plate", "2x kubejs:steel_rod", "kubejs:steel_gear", "kubejs:steel_plate"])
addAssemblerRecipe("kubejs:gold_drill_head", ["2x kubejs:gold_curved_plate", "2x kubejs:gold_rod", "kubejs:gold_gear", "kubejs:gold_plate"])

addAssemblerRecipe("4x kubejs:copper_drill", ["kubejs:copper_drill_head", "2x kubejs:iron_gear", "2x kubejs:iron_rod"])
addAssemblerRecipe("4x kubejs:bronze_drill", ["kubejs:bronze_drill_head", "2x kubejs:iron_gear", "2x kubejs:iron_rod"])
addAssemblerRecipe("4x kubejs:steel_drill", ["kubejs:steel_drill_head", "2x kubejs:iron_gear", "2x kubejs:motor", "kubejs:analog_circuit"])
addAssemblerRecipe("4x kubejs:gold_drill", ["kubejs:gold_drill_head", "2x kubejs:iron_gear", "2x kubejs:motor", "kubejs:analog_circuit"])

addAssemblerRecipe("kubejs:capacitor", ["2x kubejs:gold_plate", "2x kubejs:copper_wire", "kubejs:battery_alloy_plate"])
addAssemblerRecipe("kubejs:resistor", ["minecraft:brick", "6x kubejs:copper_wire"])
addAssemblerRecipe("kubejs:inductor", ["kubejs:steel_rod", "8x kubejs:copper_wire"])
addAssemblerRecipe("kubejs:analog_circuit", ["kubejs:lapis_lazuli_plate", "2x kubejs:copper_wire", "2x kubejs:capacitor", "2x kubejs:resistor", "kubejs:inductor"])
addAssemblerRecipe("kubejs:motor", ["4x kubejs:copper_wire", "2x kubejs:steel_curved_plate", "kubejs:steel_gear", "kubejs:steel_rod"])

addAssemblerRecipe("kubejs:brass_gear", ["4x kubejs:brass_plate", "kubejs:brass_ring"])
addAssemblerRecipe("kubejs:bronze_gear", ["4x kubejs:bronze_plate", "kubejs:bronze_ring"])
addAssemblerRecipe("kubejs:copper_gear", ["4x kubejs:copper_plate", "kubejs:copper_ring"])
addAssemblerRecipe("kubejs:diamond_gear", ["4x kubejs:diamond_plate", "kubejs:diamond_ring"])
addAssemblerRecipe("kubejs:emerald_gear", ["4x kubejs:emerald_plate", "kubejs:emerald_ring"])
addAssemblerRecipe("kubejs:gold_gear", ["4x kubejs:gold_plate", "kubejs:gold_ring"])
addAssemblerRecipe("kubejs:invar_gear", ["4x kubejs:invar_plate", "kubejs:invar_ring"])
addAssemblerRecipe("kubejs:iron_gear", ["4x kubejs:iron_plate", "kubejs:iron_ring"])
addAssemblerRecipe("kubejs:lapis_lazuli_gear", ["4x kubejs:lapis_lazuli_plate", "kubejs:lapis_lazuli_ring"])
addAssemblerRecipe("kubejs:lead_gear", ["4x kubejs:lead_plate", "kubejs:lead_ring"])
addAssemblerRecipe("kubejs:nickel_gear", ["4x kubejs:nickel_plate", "kubejs:nickel_ring"])
addAssemblerRecipe("kubejs:steel_gear", ["4x kubejs:steel_plate", "kubejs:steel_ring"])
addAssemblerRecipe("kubejs:tin_gear", ["4x kubejs:tin_plate", "kubejs:tin_ring"])
addAssemblerRecipe("kubejs:zinc_gear", ["4x kubejs:zinc_plate", "kubejs:zinc_ring"])

addAssemblerRecipe("kubejs:brass_rotor", ["4x kubejs:brass_curved_plate", "kubejs:brass_rod", "kubejs:brass_ring"])
addAssemblerRecipe("kubejs:bronze_rotor", ["4x kubejs:bronze_curved_plate", "kubejs:bronze_rod", "kubejs:bronze_ring"])
addAssemblerRecipe("kubejs:copper_rotor", ["4x kubejs:copper_curved_plate", "kubejs:copper_rod", "kubejs:copper_ring"])
addAssemblerRecipe("kubejs:diamond_rotor", ["4x kubejs:diamond_curved_plate", "kubejs:diamond_rod", "kubejs:diamond_ring"])
addAssemblerRecipe("kubejs:emerald_rotor", ["4x kubejs:emerald_curved_plate", "kubejs:emerald_rod", "kubejs:emerald_ring"])
addAssemblerRecipe("kubejs:gold_rotor", ["4x kubejs:gold_curved_plate", "kubejs:gold_rod", "kubejs:gold_ring"])
addAssemblerRecipe("kubejs:invar_rotor", ["4x kubejs:invar_curved_plate", "kubejs:invar_rod", "kubejs:invar_ring"])
addAssemblerRecipe("kubejs:iron_rotor", ["4x kubejs:iron_curved_plate", "kubejs:iron_rod", "kubejs:iron_ring"])
addAssemblerRecipe("kubejs:lapis_lazuli_rotor", ["4x kubejs:lapis_lazuli_curved_plate", "kubejs:lapis_lazuli_rod", "kubejs:lapis_lazuli_ring"])
addAssemblerRecipe("kubejs:lead_rotor", ["4x kubejs:lead_curved_plate", "kubejs:lead_rod", "kubejs:lead_ring"])
addAssemblerRecipe("kubejs:nickel_rotor", ["4x kubejs:nickel_curved_plate", "kubejs:nickel_rod", "kubejs:nickel_ring"])
addAssemblerRecipe("kubejs:steel_rotor", ["4x kubejs:steel_curved_plate", "kubejs:steel_rod", "kubejs:steel_ring"])
addAssemblerRecipe("kubejs:tin_rotor", ["4x kubejs:tin_curved_plate", "kubejs:tin_rod", "kubejs:tin_ring"])
addAssemblerRecipe("kubejs:zinc_rotor", ["4x kubejs:zinc_curved_plate", "kubejs:zinc_rod", "kubejs:zinc_ring"])
