function addCuttingMachineRecipes(material){
    // rod from plate
    addCuttingMachineRecipe(`3x kubejs:${material}_rod`, `kubejs:${material}_plate`);

    // bolt from rod
    addCuttingMachineRecipe(`2x kubejs:${material}_bolt`, `kubejs:${material}_rod`);
}

//addCuttingMachineRecipes("aluminum")
addCuttingMachineRecipes("brass")
addCuttingMachineRecipes("bronze")
//addCuttingMachineRecipes("cobalt")
//addCuttingMachineRecipes("constantan")
addCuttingMachineRecipes("copper")
addCuttingMachineRecipes("diamond")
//addCuttingMachineRecipes("electrum")
addCuttingMachineRecipes("emerald")
addCuttingMachineRecipes("gold")
addCuttingMachineRecipes("invar")
//addCuttingMachineRecipes("iridium")
//addCuttingMachineRecipes("iridium_alloy")
addCuttingMachineRecipes("iron")
addCuttingMachineRecipes("lapis_lazuli")
addCuttingMachineRecipes("lead")
addCuttingMachineRecipes("nickel")
//addCuttingMachineRecipes("platinum")
addCuttingMachineRecipes("steel")
addCuttingMachineRecipes("tin")
//addCuttingMachineRecipes("titanium")
addCuttingMachineRecipes("zinc")


// log to stripped log
addCuttingMachineRecipe("minecraft:stripped_oak_log", "minecraft:oak_log")
addCuttingMachineRecipe("minecraft:stripped_spruce_log", "minecraft:spruce_log")
addCuttingMachineRecipe("minecraft:stripped_birch_log", "minecraft:birch_log")
addCuttingMachineRecipe("minecraft:stripped_jungle_log", "minecraft:jungle_log")
addCuttingMachineRecipe("minecraft:stripped_acacia_log", "minecraft:acacia_log")
addCuttingMachineRecipe("minecraft:stripped_dark_oak_log", "minecraft:dark_oak_log")
addCuttingMachineRecipe("minecraft:stripped_mangrove_log", "minecraft:mangrove_log")
addCuttingMachineRecipe("minecraft:stripped_cherry_log", "minecraft:cherry_log")
addCuttingMachineRecipe("minecraft:stripped_crimson_stem", "minecraft:crimson_stem")
addCuttingMachineRecipe("minecraft:stripped_warped_stem", "minecraft:warped_stem")
addCuttingMachineRecipe("biomesoplenty:stripped_fir_log", "biomesoplenty:fir_log")
addCuttingMachineRecipe("biomesoplenty:stripped_redwood_log", "biomesoplenty:redwood_log")
addCuttingMachineRecipe("biomesoplenty:stripped_mahogany_log", "biomesoplenty:mahogany_log")
addCuttingMachineRecipe("biomesoplenty:stripped_jacaranda_log", "biomesoplenty:jacaranda_log")
addCuttingMachineRecipe("biomesoplenty:stripped_palm_log", "biomesoplenty:palm_log")
addCuttingMachineRecipe("biomesoplenty:stripped_willow_log", "biomesoplenty:willow_log")
addCuttingMachineRecipe("biomesoplenty:stripped_dead_log", "biomesoplenty:dead_log")
addCuttingMachineRecipe("biomesoplenty:stripped_magic_log", "biomesoplenty:magic_log")
addCuttingMachineRecipe("biomesoplenty:stripped_umbran_log", "biomesoplenty:umbran_log")
addCuttingMachineRecipe("biomesoplenty:stripped_hellbark_log", "biomesoplenty:hellbark_log")

// stripped log to planks
addCuttingMachineRecipe("8x minecraft:oak_planks", "minecraft:stripped_oak_log")
addCuttingMachineRecipe("8x minecraft:spruce_planks", "minecraft:stripped_spruce_log")
addCuttingMachineRecipe("8x minecraft:birch_planks", "minecraft:stripped_birch_log")
addCuttingMachineRecipe("8x minecraft:jungle_planks", "minecraft:stripped_jungle_log")
addCuttingMachineRecipe("8x minecraft:acacia_planks", "minecraft:stripped_acacia_log")
addCuttingMachineRecipe("8x minecraft:dark_oak_planks", "minecraft:stripped_dark_oak_log")
addCuttingMachineRecipe("8x minecraft:mangrove_planks", "minecraft:stripped_mangrove_log")
addCuttingMachineRecipe("8x minecraft:cherry_planks", "minecraft:stripped_cherry_log")
addCuttingMachineRecipe("8x minecraft:crimson_planks", "minecraft:stripped_crimson_stem")
addCuttingMachineRecipe("8x minecraft:warped_planks", "minecraft:stripped_warped_stem")
addCuttingMachineRecipe("8x biomesoplenty:fir_planks", "biomesoplenty:stripped_fir_log")
addCuttingMachineRecipe("8x biomesoplenty:redwood_planks", "biomesoplenty:stripped_redwood_log")
addCuttingMachineRecipe("8x biomesoplenty:mahogany_planks", "biomesoplenty:stripped_mahogany_log")
addCuttingMachineRecipe("8x biomesoplenty:jacaranda_planks", "biomesoplenty:stripped_jacaranda_log")
addCuttingMachineRecipe("8x biomesoplenty:palm_planks", "biomesoplenty:stripped_palm_log")
addCuttingMachineRecipe("8x biomesoplenty:willow_planks", "biomesoplenty:stripped_willow_log")
addCuttingMachineRecipe("8x biomesoplenty:dead_planks", "biomesoplenty:stripped_dead_log")
addCuttingMachineRecipe("8x biomesoplenty:magic_planks", "biomesoplenty:stripped_magic_log")
addCuttingMachineRecipe("8x biomesoplenty:umbran_planks", "biomesoplenty:stripped_umbran_log")
addCuttingMachineRecipe("8x biomesoplenty:hellbark_planks", "biomesoplenty:stripped_hellbark_log")


// wood to stripped wood
addCuttingMachineRecipe("minecraft:stripped_oak_wood", "minecraft:oak_wood")
addCuttingMachineRecipe("minecraft:stripped_spruce_wood", "minecraft:spruce_wood")
addCuttingMachineRecipe("minecraft:stripped_birch_wood", "minecraft:birch_wood")
addCuttingMachineRecipe("minecraft:stripped_jungle_wood", "minecraft:jungle_wood")
addCuttingMachineRecipe("minecraft:stripped_acacia_wood", "minecraft:acacia_wood")
addCuttingMachineRecipe("minecraft:stripped_dark_oak_wood", "minecraft:dark_oak_wood")
addCuttingMachineRecipe("minecraft:stripped_mangrove_wood", "minecraft:mangrove_wood")
addCuttingMachineRecipe("minecraft:stripped_cherry_wood", "minecraft:cherry_wood")
addCuttingMachineRecipe("minecraft:stripped_crimson_hyphae", "minecraft:crimson_hyphae")
addCuttingMachineRecipe("minecraft:stripped_warped_hyphae", "minecraft:warped_hyphae")
addCuttingMachineRecipe("biomesoplenty:stripped_fir_wood", "biomesoplenty:fir_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_redwood_wood", "biomesoplenty:redwood_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_mahogany_wood", "biomesoplenty:mahogany_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_jacaranda_wood", "biomesoplenty:jacaranda_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_palm_wood", "biomesoplenty:palm_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_willow_wood", "biomesoplenty:willow_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_dead_wood", "biomesoplenty:dead_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_magic_wood", "biomesoplenty:magic_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_umbran_wood", "biomesoplenty:umbran_wood")
addCuttingMachineRecipe("biomesoplenty:stripped_hellbark_wood", "biomesoplenty:hellbark_wood")


// stripped wood to planks
addCuttingMachineRecipe("8x minecraft:oak_planks", "minecraft:stripped_oak_wood")
addCuttingMachineRecipe("8x minecraft:spruce_planks", "minecraft:stripped_spruce_wood")
addCuttingMachineRecipe("8x minecraft:birch_planks", "minecraft:stripped_birch_wood")
addCuttingMachineRecipe("8x minecraft:jungle_planks", "minecraft:stripped_jungle_wood")
addCuttingMachineRecipe("8x minecraft:acacia_planks", "minecraft:stripped_acacia_wood")
addCuttingMachineRecipe("8x minecraft:dark_oak_planks", "minecraft:stripped_dark_oak_wood")
addCuttingMachineRecipe("8x minecraft:mangrove_planks", "minecraft:stripped_mangrove_wood")
addCuttingMachineRecipe("8x minecraft:cherry_planks", "minecraft:stripped_cherry_wood")
addCuttingMachineRecipe("8x minecraft:crimson_planks", "minecraft:stripped_crimson_hyphae")
addCuttingMachineRecipe("8x minecraft:warped_planks", "minecraft:stripped_warped_hyphae")
addCuttingMachineRecipe("8x biomesoplenty:fir_planks", "biomesoplenty:stripped_fir_wood")
addCuttingMachineRecipe("8x biomesoplenty:redwood_planks", "biomesoplenty:stripped_redwood_wood")
addCuttingMachineRecipe("8x biomesoplenty:mahogany_planks", "biomesoplenty:stripped_mahogany_wood")
addCuttingMachineRecipe("8x biomesoplenty:jacaranda_planks", "biomesoplenty:stripped_jacaranda_wood")
addCuttingMachineRecipe("8x biomesoplenty:palm_planks", "biomesoplenty:stripped_palm_wood")
addCuttingMachineRecipe("8x biomesoplenty:willow_planks", "biomesoplenty:stripped_willow_wood")
addCuttingMachineRecipe("8x biomesoplenty:dead_planks", "biomesoplenty:stripped_dead_wood")
addCuttingMachineRecipe("8x biomesoplenty:magic_planks", "biomesoplenty:stripped_magic_wood")
addCuttingMachineRecipe("8x biomesoplenty:umbran_planks", "biomesoplenty:stripped_umbran_wood")
addCuttingMachineRecipe("8x biomesoplenty:hellbark_planks", "biomesoplenty:stripped_hellbark_wood")
