// raw material from ore
addMaceratorRecipe("5x kubejs:aluminum_raw_material", "2x kubejs:aluminum_ore", 400)
addMaceratorRecipe("5x kubejs:aluminum_raw_material", "2x kubejs:aluminum_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:bismuth_raw_material", "2x kubejs:bismuth_ore", 400)
addMaceratorRecipe("5x kubejs:bismuth_raw_material", "2x kubejs:bismuth_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:cobalt_raw_material", "2x kubejs:cobalt_ore", 400)
addMaceratorRecipe("5x minecraft:raw_copper", "2x minecraft:copper_ore", 400)
addMaceratorRecipe("5x minecraft:raw_copper", "2x minecraft:deepslate_copper_ore", 400)
addMaceratorRecipe("5x minecraft:raw_gold", "2x minecraft:gold_ore", 400)
addMaceratorRecipe("5x minecraft:raw_gold", "2x minecraft:deepslate_gold_ore", 400)
addMaceratorRecipe("5x kubejs:iridium_raw_material", "2x kubejs:iridium_ore", 400)
addMaceratorRecipe("5x kubejs:iridium_raw_material", "2x kubejs:iridium_ore_deepslate", 400)
addMaceratorRecipe("5x minecraft:raw_iron", "2x minecraft:iron_ore", 400)
addMaceratorRecipe("5x minecraft:raw_iron", "2x minecraft:deepslate_iron_ore", 400)
addMaceratorRecipe("5x kubejs:magnesium_raw_material", "2x kubejs:magnesium_ore", 400)
addMaceratorRecipe("5x kubejs:magnesium_raw_material", "2x kubejs:magnesium_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:nickel_raw_material", "2x kubejs:nickel_ore", 400)
addMaceratorRecipe("5x kubejs:nickel_raw_material", "2x kubejs:nickel_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:osmium_raw_material", "2x kubejs:osmium_ore", 400)
addMaceratorRecipe("5x kubejs:osmium_raw_material", "2x kubejs:osmium_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:platinum_raw_material", "2x kubejs:platinum_ore", 400)
addMaceratorRecipe("5x kubejs:platinum_raw_material", "2x kubejs:platinum_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:silver_raw_material", "2x kubejs:silver_ore", 400)
addMaceratorRecipe("5x kubejs:silver_raw_material", "2x kubejs:silver_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:tin_raw_material", "2x kubejs:tin_ore", 400)
addMaceratorRecipe("5x kubejs:tin_raw_material", "2x kubejs:tin_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:titanium_raw_material", "2x kubejs:titanium_ore", 400)
addMaceratorRecipe("5x kubejs:tungsten_raw_material", "2x kubejs:tungsten_ore", 400)
addMaceratorRecipe("5x kubejs:tungsten_raw_material", "2x kubejs:tungsten_ore_deepslate", 400)
addMaceratorRecipe("5x kubejs:zinc_raw_material", "2x kubejs:zinc_ore", 400)
addMaceratorRecipe("5x kubejs:zinc_raw_material", "2x kubejs:zinc_ore_deepslate", 400)


// raw material from crushed ore
addMaceratorRecipe("3x kubejs:aluminum_raw_material", "2x kubejs:crushed_aluminum_ore", 400)
addMaceratorRecipe("3x kubejs:bismuth_raw_material", "2x kubejs:crushed_bismuth_ore", 400)
addMaceratorRecipe("3x kubejs:cobalt_raw_material", "2x kubejs:crushed_cobalt_ore", 400)
addMaceratorRecipe("3x minecraft:raw_copper", "2x kubejs:crushed_copper_ore", 400)
addMaceratorRecipe("3x minecraft:raw_gold", "2x kubejs:crushed_gold_ore", 400)
addMaceratorRecipe("3x kubejs:iridium_raw_material", "2x kubejs:crushed_iridium_ore", 400)
addMaceratorRecipe("3x minecraft:raw_iron", "2x kubejs:crushed_iron_ore", 400)
addMaceratorRecipe("3x kubejs:magnesium_raw_material", "2x kubejs:crushed_magnesium_ore", 400)
addMaceratorRecipe("3x kubejs:nickel_raw_material", "2x kubejs:crushed_nickel_ore", 400)
addMaceratorRecipe("3x kubejs:osmium_raw_material", "2x kubejs:crushed_osmium_ore", 400)
addMaceratorRecipe("3x kubejs:platinum_raw_material", "2x kubejs:crushed_platinum_ore", 400)
addMaceratorRecipe("3x kubejs:silver_raw_material", "2x kubejs:crushed_silver_ore", 400)
addMaceratorRecipe("3x kubejs:tin_raw_material", "2x kubejs:crushed_tin_ore", 400)
addMaceratorRecipe("3x kubejs:titanium_raw_material", "2x kubejs:crushed_titanium_ore", 400)
addMaceratorRecipe("3x kubejs:tungsten_raw_material", "2x kubejs:crushed_tungsten_ore", 400)
addMaceratorRecipe("3x kubejs:zinc_raw_material", "2x kubejs:crushed_zinc_ore", 400)


// dust from raw material
addMaceratorRecipe("3x kubejs:aluminum_dust", "2x kubejs:aluminum_raw_material", 400)
addMaceratorRecipe("3x kubejs:bismuth_dust", "2x kubejs:bismuth_raw_material", 400)
addMaceratorRecipe("3x kubejs:cobalt_dust", "2x kubejs:cobalt_raw_material", 400)
addMaceratorRecipe("3x kubejs:copper_dust", "2x minecraft:raw_copper", 400)
addMaceratorRecipe("3x kubejs:gold_dust", "2x minecraft:raw_gold", 400)
addMaceratorRecipe("3x kubejs:iridium_dust", "2x kubejs:iridium_raw_material", 400)
addMaceratorRecipe("3x kubejs:iron_dust", "2x minecraft:raw_iron", 400)
addMaceratorRecipe("3x kubejs:magnesium_dust", "2x kubejs:magnesium_raw_material", 400)
addMaceratorRecipe("3x kubejs:nickel_dust", "2x kubejs:nickel_raw_material", 400)
addMaceratorRecipe("3x kubejs:osmium_dust", "2x kubejs:osmium_raw_material", 400)
addMaceratorRecipe("3x kubejs:platinum_dust", "2x kubejs:platinum_raw_material", 400)
addMaceratorRecipe("3x kubejs:silver_dust", "2x kubejs:silver_raw_material", 400)
addMaceratorRecipe("3x kubejs:tin_dust", "2x kubejs:tin_raw_material", 400)
addMaceratorRecipe("3x kubejs:titanium_dust", "2x kubejs:titanium_raw_material", 400)
addMaceratorRecipe("3x kubejs:tungsten_dust", "2x kubejs:tungsten_raw_material", 400)
addMaceratorRecipe("3x kubejs:zinc_dust", "2x kubejs:zinc_raw_material", 400)


// dust from ingot
addMaceratorRecipe("kubejs:advanced_alloy_dust", "kubejs:advanced_alloy_ingot")
addMaceratorRecipe("kubejs:aluminum_dust", "kubejs:aluminum_ingot")
addMaceratorRecipe("kubejs:bismuth_dust", "kubejs:bismuth_ingot")
addMaceratorRecipe("kubejs:brass_dust", "kubejs:brass_ingot")
addMaceratorRecipe("kubejs:bronze_dust", "kubejs:bronze_ingot")
addMaceratorRecipe("kubejs:cobalt_dust", "kubejs:cobalt_ingot")
addMaceratorRecipe("kubejs:constantan_dust", "kubejs:constantan_ingot")
addMaceratorRecipe("kubejs:copper_dust", "minecraft:copper_ingot")
addMaceratorRecipe("kubejs:diamond_dust", "minecraft:diamond")
addMaceratorRecipe("kubejs:electrum_dust", "kubejs:electrum_ingot")
addMaceratorRecipe("kubejs:emerald_dust", "minecraft:emerald")
addMaceratorRecipe("kubejs:enderium_dust", "kubejs:enderium_ingot")
addMaceratorRecipe("kubejs:gold_dust", "minecraft:gold_ingot")
addMaceratorRecipe("kubejs:invar_dust", "kubejs:invar_ingot")
addMaceratorRecipe("kubejs:iridium_dust", "kubejs:iridium_ingot")
addMaceratorRecipe("kubejs:iridium_alloy_dust", "kubejs:iridium_alloy_ingot")
addMaceratorRecipe("kubejs:iron_dust", "minecraft:iron_ingot")
addMaceratorRecipe("kubejs:lapis_lazuli_dust", "minecraft:lapis_lazuli")
addMaceratorRecipe("kubejs:lead_dust", "kubejs:lead_ingot")
addMaceratorRecipe("kubejs:lumium_dust", "kubejs:lumium_ingot")
addMaceratorRecipe("kubejs:magnesium_dust", "kubejs:magnesium_ingot")
addMaceratorRecipe("kubejs:nickel_dust", "kubejs:nickel_ingot")
addMaceratorRecipe("kubejs:osmium_dust", "kubejs:osmium_ingot")
addMaceratorRecipe("kubejs:platinum_dust", "kubejs:platinum_ingot")
addMaceratorRecipe("kubejs:refined_glowstone_dust", "kubejs:refined_glowstone_ingot")
addMaceratorRecipe("kubejs:refined_obsidian_dust", "kubejs:refined_obsidian_ingot")
addMaceratorRecipe("kubejs:signalum_dust", "kubejs:signalum_ingot")
addMaceratorRecipe("kubejs:silver_dust", "kubejs:silver_ingot")
addMaceratorRecipe("kubejs:steel_dust", "kubejs:steel_ingot")
addMaceratorRecipe("kubejs:tin_dust", "kubejs:tin_ingot")
addMaceratorRecipe("kubejs:titanium_dust", "kubejs:titanium_ingot")
addMaceratorRecipe("kubejs:tungsten_dust", "kubejs:tungsten_ingot")
addMaceratorRecipe("kubejs:zinc_dust", "kubejs:zinc_ingot")


// dust from plate
addMaceratorRecipe("kubejs:advanced_alloy_dust", "kubejs:advanced_alloy_plate")
addMaceratorRecipe("kubejs:aluminum_dust", "kubejs:aluminum_plate")
addMaceratorRecipe("kubejs:bismuth_dust", "kubejs:bismuth_plate")
addMaceratorRecipe("kubejs:brass_dust", "kubejs:brass_plate")
addMaceratorRecipe("kubejs:bronze_dust", "kubejs:bronze_plate")
addMaceratorRecipe("kubejs:cobalt_dust", "kubejs:cobalt_plate")
addMaceratorRecipe("kubejs:constantan_dust", "kubejs:constantan_plate")
addMaceratorRecipe("kubejs:copper_dust", "kubejs:copper_plate")
addMaceratorRecipe("kubejs:diamond_dust", "kubejs:diamond_plate")
addMaceratorRecipe("kubejs:electrum_dust", "kubejs:electrum_plate")
addMaceratorRecipe("kubejs:emerald_dust", "kubejs:emerald_plate")
addMaceratorRecipe("kubejs:enderium_dust", "kubejs:enderium_plate")
addMaceratorRecipe("kubejs:gold_dust", "kubejs:gold_plate")
addMaceratorRecipe("kubejs:invar_dust", "kubejs:invar_plate")
addMaceratorRecipe("kubejs:iridium_dust", "kubejs:iridium_plate")
addMaceratorRecipe("kubejs:iridium_alloy_dust", "kubejs:iridium_alloy_plate")
addMaceratorRecipe("kubejs:iron_dust", "kubejs:iron_plate")
addMaceratorRecipe("kubejs:lapis_lazuli_dust", "kubejs:lapis_lazuli_plate")
addMaceratorRecipe("kubejs:lead_dust", "kubejs:lead_plate")
addMaceratorRecipe("kubejs:lumium_dust", "kubejs:lumium_plate")
addMaceratorRecipe("kubejs:magnesium_dust", "kubejs:magnesium_plate")
addMaceratorRecipe("kubejs:nickel_dust", "kubejs:nickel_plate")
addMaceratorRecipe("kubejs:osmium_dust", "kubejs:osmium_plate")
addMaceratorRecipe("kubejs:platinum_dust", "kubejs:platinum_plate")
addMaceratorRecipe("kubejs:refined_glowstone_dust", "kubejs:refined_glowstone_plate")
addMaceratorRecipe("kubejs:refined_obsidian_dust", "kubejs:refined_obsidian_plate")
addMaceratorRecipe("kubejs:signalum_dust", "kubejs:signalum_plate")
addMaceratorRecipe("kubejs:silver_dust", "kubejs:silver_plate")
addMaceratorRecipe("kubejs:steel_dust", "kubejs:steel_plate")
addMaceratorRecipe("kubejs:tin_dust", "kubejs:tin_plate")
addMaceratorRecipe("kubejs:titanium_dust", "kubejs:titanium_plate")
addMaceratorRecipe("kubejs:tungsten_dust", "kubejs:tungsten_plate")
addMaceratorRecipe("kubejs:zinc_dust", "kubejs:zinc_plate")


// dust from rod
addMaceratorRecipe("kubejs:advanced_alloy_dust", "2x kubejs:advanced_alloy_rod")
addMaceratorRecipe("kubejs:aluminum_dust", "2x kubejs:aluminum_rod")
addMaceratorRecipe("kubejs:bismuth_dust", "2x kubejs:bismuth_rod")
addMaceratorRecipe("kubejs:brass_dust", "2x kubejs:brass_rod")
addMaceratorRecipe("kubejs:bronze_dust", "2x kubejs:bronze_rod")
addMaceratorRecipe("kubejs:cobalt_dust", "2x kubejs:cobalt_rod")
addMaceratorRecipe("kubejs:constantan_dust", "2x kubejs:constantan_rod")
addMaceratorRecipe("kubejs:copper_dust", "2x kubejs:copper_rod")
addMaceratorRecipe("kubejs:diamond_dust", "2x kubejs:diamond_rod")
addMaceratorRecipe("kubejs:electrum_dust", "2x kubejs:electrum_rod")
addMaceratorRecipe("kubejs:emerald_dust", "2x kubejs:emerald_rod")
addMaceratorRecipe("kubejs:enderium_dust", "2x kubejs:enderium_rod")
addMaceratorRecipe("kubejs:gold_dust", "2x kubejs:gold_rod")
addMaceratorRecipe("kubejs:invar_dust", "2x kubejs:invar_rod")
addMaceratorRecipe("kubejs:iridium_dust", "2x kubejs:iridium_rod")
addMaceratorRecipe("kubejs:iridium_alloy_dust", "2x kubejs:iridium_alloy_rod")
addMaceratorRecipe("kubejs:iron_dust", "2x kubejs:iron_rod")
addMaceratorRecipe("kubejs:lapis_lazuli_dust", "2x kubejs:lapis_lazuli_rod")
addMaceratorRecipe("kubejs:lead_dust", "2x kubejs:lead_rod")
addMaceratorRecipe("kubejs:lumium_dust", "2x kubejs:lumium_rod")
addMaceratorRecipe("kubejs:magnesium_dust", "2x kubejs:magnesium_rod")
addMaceratorRecipe("kubejs:nickel_dust", "2x kubejs:nickel_rod")
addMaceratorRecipe("kubejs:osmium_dust", "2x kubejs:osmium_rod")
addMaceratorRecipe("kubejs:platinum_dust", "2x kubejs:platinum_rod")
addMaceratorRecipe("kubejs:refined_glowstone_dust", "2x kubejs:refined_glowstone_rod")
addMaceratorRecipe("kubejs:refined_obsidian_dust", "2x kubejs:refined_obsidian_rod")
addMaceratorRecipe("kubejs:signalum_dust", "2x kubejs:signalum_rod")
addMaceratorRecipe("kubejs:silver_dust", "2x kubejs:silver_rod")
addMaceratorRecipe("kubejs:steel_dust", "2x kubejs:steel_rod")
addMaceratorRecipe("kubejs:tin_dust", "2x kubejs:tin_rod")
addMaceratorRecipe("kubejs:titanium_dust", "2x kubejs:titanium_rod")
addMaceratorRecipe("kubejs:tungsten_dust", "2x kubejs:tungsten_rod")
addMaceratorRecipe("kubejs:zinc_dust", "2x kubejs:zinc_rod")


// dust from gear
addMaceratorRecipe("4x kubejs:advanced_alloy_dust", "kubejs:advanced_alloy_gear")
addMaceratorRecipe("4x kubejs:aluminum_dust", "kubejs:aluminum_gear")
addMaceratorRecipe("4x kubejs:bismuth_dust", "kubejs:bismuth_gear")
addMaceratorRecipe("4x kubejs:brass_dust", "kubejs:brass_gear")
addMaceratorRecipe("4x kubejs:bronze_dust", "kubejs:bronze_gear")
addMaceratorRecipe("4x kubejs:cobalt_dust", "kubejs:cobalt_gear")
addMaceratorRecipe("4x kubejs:constantan_dust", "kubejs:constantan_gear")
addMaceratorRecipe("4x kubejs:copper_dust", "kubejs:copper_gear")
addMaceratorRecipe("4x kubejs:diamond_dust", "kubejs:diamond_gear")
addMaceratorRecipe("4x kubejs:electrum_dust", "kubejs:electrum_gear")
addMaceratorRecipe("4x kubejs:emerald_dust", "kubejs:emerald_gear")
addMaceratorRecipe("4x kubejs:enderium_dust", "kubejs:enderium_gear")
addMaceratorRecipe("4x kubejs:gold_dust", "kubejs:gold_gear")
addMaceratorRecipe("4x kubejs:invar_dust", "kubejs:invar_gear")
addMaceratorRecipe("4x kubejs:iridium_dust", "kubejs:iridium_gear")
addMaceratorRecipe("4x kubejs:iridium_alloy_dust", "kubejs:iridium_alloy_gear")
addMaceratorRecipe("4x kubejs:iron_dust", "kubejs:iron_gear")
addMaceratorRecipe("4x kubejs:lapis_lazuli_dust", "kubejs:lapis_lazuli_gear")
addMaceratorRecipe("4x kubejs:lead_dust", "kubejs:lead_gear")
addMaceratorRecipe("4x kubejs:lumium_dust", "kubejs:lumium_gear")
addMaceratorRecipe("4x kubejs:magnesium_dust", "kubejs:magnesium_gear")
addMaceratorRecipe("4x kubejs:nickel_dust", "kubejs:nickel_gear")
addMaceratorRecipe("4x kubejs:osmium_dust", "kubejs:osmium_gear")
addMaceratorRecipe("4x kubejs:platinum_dust", "kubejs:platinum_gear")
addMaceratorRecipe("4x kubejs:refined_glowstone_dust", "kubejs:refined_glowstone_gear")
addMaceratorRecipe("4x kubejs:refined_obsidian_dust", "kubejs:refined_obsidian_gear")
addMaceratorRecipe("4x kubejs:signalum_dust", "kubejs:signalum_gear")
addMaceratorRecipe("4x kubejs:silver_dust", "kubejs:silver_gear")
addMaceratorRecipe("4x kubejs:steel_dust", "kubejs:steel_gear")
addMaceratorRecipe("4x kubejs:tin_dust", "kubejs:tin_gear")
addMaceratorRecipe("4x kubejs:titanium_dust", "kubejs:titanium_gear")
addMaceratorRecipe("4x kubejs:tungsten_dust", "kubejs:tungsten_gear")
addMaceratorRecipe("4x kubejs:zinc_dust", "kubejs:zinc_gear")


// dust from wire
addMaceratorRecipe("kubejs:advanced_alloy_dust", "4x kubejs:advanced_alloy_wire")
addMaceratorRecipe("kubejs:aluminum_dust", "4x kubejs:aluminum_wire")
addMaceratorRecipe("kubejs:bismuth_dust", "4x kubejs:bismuth_wire")
addMaceratorRecipe("kubejs:brass_dust", "4x kubejs:brass_wire")
addMaceratorRecipe("kubejs:bronze_dust", "4x kubejs:bronze_wire")
addMaceratorRecipe("kubejs:cobalt_dust", "4x kubejs:cobalt_wire")
addMaceratorRecipe("kubejs:constantan_dust", "4x kubejs:constantan_wire")
addMaceratorRecipe("kubejs:copper_dust", "4x kubejs:copper_wire")
addMaceratorRecipe("kubejs:diamond_dust", "4x kubejs:diamond_wire")
addMaceratorRecipe("kubejs:electrum_dust", "4x kubejs:electrum_wire")
addMaceratorRecipe("kubejs:emerald_dust", "4x kubejs:emerald_wire")
addMaceratorRecipe("kubejs:enderium_dust", "4x kubejs:enderium_wire")
addMaceratorRecipe("kubejs:gold_dust", "4x kubejs:gold_wire")
addMaceratorRecipe("kubejs:invar_dust", "4x kubejs:invar_wire")
addMaceratorRecipe("kubejs:iridium_dust", "4x kubejs:iridium_wire")
addMaceratorRecipe("kubejs:iridium_alloy_dust", "4x kubejs:iridium_alloy_wire")
addMaceratorRecipe("kubejs:iron_dust", "4x kubejs:iron_wire")
addMaceratorRecipe("kubejs:lapis_lazuli_dust", "4x kubejs:lapis_lazuli_wire")
addMaceratorRecipe("kubejs:lead_dust", "4x kubejs:lead_wire")
addMaceratorRecipe("kubejs:lumium_dust", "4x kubejs:lumium_wire")
addMaceratorRecipe("kubejs:magnesium_dust", "4x kubejs:magnesium_wire")
addMaceratorRecipe("kubejs:nickel_dust", "4x kubejs:nickel_wire")
addMaceratorRecipe("kubejs:osmium_dust", "4x kubejs:osmium_wire")
addMaceratorRecipe("kubejs:platinum_dust", "4x kubejs:platinum_wire")
addMaceratorRecipe("kubejs:refined_glowstone_dust", "4x kubejs:refined_glowstone_wire")
addMaceratorRecipe("kubejs:refined_obsidian_dust", "4x kubejs:refined_obsidian_wire")
addMaceratorRecipe("kubejs:signalum_dust", "4x kubejs:signalum_wire")
addMaceratorRecipe("kubejs:silver_dust", "4x kubejs:silver_wire")
addMaceratorRecipe("kubejs:steel_dust", "4x kubejs:steel_wire")
addMaceratorRecipe("kubejs:tin_dust", "4x kubejs:tin_wire")
addMaceratorRecipe("kubejs:titanium_dust", "4x kubejs:titanium_wire")
addMaceratorRecipe("kubejs:tungsten_dust", "4x kubejs:tungsten_wire")
addMaceratorRecipe("kubejs:zinc_dust", "4x kubejs:zinc_wire")
